---
title: 错误
slug: zh-CN/v2/guides/errors
---

## 概述

一些错误对象可能包含 `.cause` 属性。大多数情况下，它类型为 `unknown`，其值可能会在将来发生变化，恕不另行通知。

## 通用

### SurrealError

`SurrealError` 是这个 SDK 明确抛出的几乎所有错误对象的基类。它继承了 JavaScript 的 `Error` 类。这个错误对象很少被单独抛出，通常被具有特殊意义的子类错误对象所继承。建议使用 `try-catch` 语法捕捉它，以方便识别错误是否由这个 SDK 明确抛出。

#### 属性

`.name: "SurrealError"`
:   错误名称。

`.message`
:   错误消息。

`.stack`
:   可能包含堆栈跟踪。

`.cause`
:   可能包含导致错误的原因或上下文。

### SurrealTypeError

继承自: `SurrealError`

当输入值或其他验证失败时抛出此错误。

#### 属性

`.name: "SurrealTypeError"`
:   错误名称。

`.expected`
:   预期数据类型。

`.actual`
:   实际值的字符串表示形式。

#### 解决方法

沿着堆栈跟踪查找导致输入数据类型不符合预期的原因。

### SurrealValueError

继承自: `SurrealError`

当输入值或其他验证失败时抛出此错误。

#### 属性

`.name: "SurrealValueError"`
:   错误名称。

`.expected`
:   预期数据类型。

`.actual`
:   实际值。

#### 解决方法

沿着堆栈跟踪查找导致输入数据类型不符合预期的原因。

### SurrealAggregateError

继承自: `SurrealError`

当多个错误或错误消息被汇总时抛出此错误。

#### 属性

`.name: "SurrealAggregateError"`
:   错误名称。

`.cause: unknown[]`
:   数组的每个元素包含错误或错误消息等。

### CircularReferenceError

继承自: `SurrealError`

当检测到循环引用时抛出此错误。主要发生在将 JavaScript 值转换为其他格式的过程中，当检测到父对象包含自身时抛出。

#### 属性

`.name: "CircularReferenceError"`
:   错误名称。

`.reference: unknown`
:   发生循环引用的值。

例如，在以下情况下可能会抛出此错误：

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

#### 解决方法

此错误不仅在 `toSurql` 函数中抛出，它是一种常见的错误。需要仔细调试对象，确保对象内部不包含自身。

### NumberRangeError

继承自: `SurrealError`

当数值超出范围时抛出此错误。

#### 属性

`.name: "NumberRangeError"`
:   错误名称。

`.range`
:   预期范围。

`.actual`
:   实际值。

`.integer`
:   如果为 `true`，则预期为整数。

#### 解决方法

沿着堆栈跟踪查找导致输入数据类型不符合预期的原因。

### UnsupportedRuntimeError

继承自: `SurrealError`

当检测到使用不支持的运行时环境时抛出此错误。

#### 属性

`.name: "UnsupportedRuntimeError"`
:   错误名称。

#### 解决方法

停止使用该运行时环境，或使用 polyfill 并进行充分的测试。

### UnreachableError

继承自: `SurrealError`

当到达不可到达的代码时抛出此错误。如果抛出此错误，则可能是遇到了这个 SDK 的 bug。

#### 属性

`.name: "UnreachableError"`
:   错误名称。

#### 解决方法

可以通过以下链接提交此问题：

[https://github.com/tai-kun/surrealdb.js/issues](https://github.com/tai-kun/surrealdb.js/issues)

## 客户端

### CircularEngineReferenceError

继承自: `CircularReferenceError`

当连接到数据库时，如果在引擎之间发生循环引用，则抛出此错误。

#### 属性

`.name: "CircularEngineReferenceError"`
:   错误名称。

`.reference: string`
:   发生循环引用的方案名称。

`.seen: string[]`
:   发生循环引用之前所经过的方案名称列表。

例如，在以下情况下可能会抛出此错误：

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

上面的例子中，尽管 https 协议引擎指定使用 http 协议引擎，但 http 协议引擎试图使用 https 协议引擎，从而导致循环引用错误。

#### 解决方法

不要将字符串作为协议名称的值，而是将它替换为创建引擎的具体实现：

```ts del={6} ins={7-10}
import { initSurreal } from "@tai-kun/surrealdb";
import HttpEngine from "@tai-kun/surrealdb/http-engine";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    http: config => new HttpEngine({
      ...config,
      // fetch: <your custom fetch function>
    }),
    https: "http",
  },
  // ...
});
```

### EngineNotFoundError

继承自: `SurrealError`

当试图使用没有设置引擎的协议进行连接时抛出此错误。

#### 属性

`.name: "EngineNotFoundError"`
:   错误名称。

`.scheme: string`
:   连接目标的协议名称。

例如，在以下情况下可能会抛出此错误：

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https scheme engine found.
```

#### 解决方法

检查 `engines` 属性，看看是否能够使用连接目标的协议创建引擎。

```ts ins={6}
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
    https: "http",
  },
  // ...
});
```

### ConnectionConflictError

继承自: `SurrealError`

当客户端试图同时连接到多个端点时抛出此错误。

#### 属性

`.name: "ConnectionConflictError"`
:   错误名称。

`.endpoint1: string`
:   已经连接的端点。

`.endpoint2: string`
:   另一个端点。

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("ws://localhost:8000");
await db.connect("ws://localhost:1129"); // throws ConnectionConflictError: An attempt was made to connect to ws://localhost:1129/rpc while ws://localhost:8000/rpc was already connected.
```

`.connect` 方法会自动在传入的 URL 的路径末尾添加 `/rpc`，除非路径已经以 `/rpc` 结尾。因此，如果一方的 URL 路径以 `/rpc` 结尾，则可能不会抛出错误，尽管它看起来像错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

#### 解决方法

在调用 `.connect` 方法之前调用 `.close` 方法，就可以连接到任意端点。

```ts ins={6}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.close();
await db.connect("http://localhost:11298");
```

### MissingNamespaceError

继承自: `SurrealError`

当在选择数据库之前未选择命名空间时抛出此错误。或者，当选择数据库后试图将命名空间设为未选择状态时也会抛出此错误。

#### 属性

`.name: "MissingNamespaceError"`
:   错误名称。

`.database: string`
:   数据库名称。

例如，在以下情况下可能会抛出此错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  database: "example",
}); // throws MissingNamespaceError: The namespace must be specified before the database.
```

#### 解决方法

选择数据库时，也应该选择命名空间。

```ts ins={7}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  namespace: "example",
  database: "example",
});
```

### RpcResponseError

继承自: `SurrealError`

当 RPC 响应指示错误时抛出此错误。连接的协议和响应主体解码等都没有问题，但是这意味着 SurrealDB 无法处理 RPC 请求。

#### 属性

`.name: "RpcResponseError"`
:   错误名称。

`.id?: string`
:   用于标识 RPC 请求的 ID。ID 始终以 `<方法名称>_` 开头。

`.code: number`
:   SurrealDB 文档中没有明确说明，可能是一个 JSON-RPC 错误代码。

#### 解决方法

原因多种多样，可能是这个 SDK 支持的 SurrelDB 版本和处理 RPC 请求的 SurrealDB 版本不一致。

### QueryFailedError

继承自: `SurrealAggregateError`

当查询失败时抛出此错误。

#### 属性

`.name: "QueryFailedError"`
:   错误名称。

`.cause: string[]`
:   错误列表。

例如，在以下情况下可能会抛出此错误：

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

#### 解决方法

检查 SurrelQL 语法是否正确。

### Closed

继承自: `SurrealError`

表明连接已被强制关闭。

#### 属性

`.name: "Closed"`
:   错误名称。

例如，在以下情况下会得到此错误：

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## 引擎

### EngineError

继承自: `SurrealError`

表明错误源自引擎。它通过事件监听器发送。

#### 属性

`.name: "EngineError"`
:   错误名称。

`.fatal: boolean | undefined`
:   表明错误是否致命。

### HttpEngineError

继承自: `EngineError`

表明错误源自 HTTP 引擎。目前只是定义，尚未使用。

#### 属性

`.name: "HttpEngineError"`
:   错误名称。

### WebSocketEngineError

继承自: `EngineError`

表明错误源自 WebSocket 引擎。当在解析响应主体之前找不到用于标识 RPC 请求的 ID，或者当从 WebSocket 对象接收到错误事件或切断 WebSocket 连接时使用。

这个 SDK 使用 `315x` 作为自定义状态码。此范围在 [IANA](https://www.iana.org/assignments/websocket/websocket.xml#close-code-number) 中是未分配的状态码。

#### 属性

`.name: "WebSocketEngineError"`
:   错误名称。

`.code: number`
:   下列状态码之一：
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: 表明从 `WebSocket`[^1] 实例接收到 "error" 事件。
    - `3151`: 表明在 WebSocket 引擎注册的 "open" 事件处理程序中发生了错误。大多数情况下，发生在连接中状态到连接状态的转换过程中，存在 `StateTransitionError`。
    - `3152`: 表明在 WebSocket 引擎注册的 "message" 事件处理程序中发生了错误。原因多种多样，但最有可能的是在事件处理程序中抛出了 `ServerResponseError` 或 `RpcResponseError`。可能是由于请求时使用了无效的 RPC 参数。在这种情况下，RPC 调用方法（默认情况下）会在 5 秒后超时并失败。在 SurrealDB v2.0.2 之前的版本中，可能存在更广泛的原因导致超时。
    - `3153`: 表明 ping 的发送或接收失败。这可能是暂时的错误，但如果持续发生，则可能是连接无法保持。
    - `3154`: 表明在 WebSocket 引擎注册的 "close" 事件处理程序中发生了错误。大多数情况下，发生在断开连接状态到断开连接状态的转换过程中，存在 `StateTransitionError`。
:   注意，不包括下列状态码，因为这个 SDK 不会将它们视为错误：
    - `1000`: 正常断开连接。
    - `1001`: 提前断开连接很常见。
    - `1004`: 已保留。
    - `1005`: 已保留。
    - `1006`: 已保留。
    - `1015`: 已保留。

^1: `WebSocket` 可以是运行时环境在全局变量中定义的类，也可以是 `ws` 的类。

#### 解决方法

`1002`,`1003`,`1007`...`1011`,`1014`,`3150`,`3151`,`3154`
:   可能没有自动恢复的方法。需要修改运行时环境、SurrealDB 配置或硬编码实现。

`3152`
:   检查传递给方法的参数（即 RPC 请求内容）是否正确。

`1012`,`1013`,`3153`
:   可以使用实验性的功能 [`autoReconnect()`](/v2/experimental/auto-reconnect) 来尝试自动恢复。

### StateTransitionError

继承自: `SurrealAggregateError`

当在状态转换过程中执行事件监听器失败时抛出此错误。

#### 属性

`.name: "StateTransitionError"`
:   错误名称。

`.from: string`
:   状态转换开始时的状态。

`.to: string`
:   目标状态。

`.fallback: string`
:   状态转换失败时的备用目标状态。如果 `.to` 与其相同，则表明它是强制转换的。

例如，在以下情况下可能会抛出此错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

db.on("connecting", () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

### ConnectionUnavailableError

继承自: `SurrealError`

当试图在未连接的情况下发送 RPC 请求时抛出此错误。

#### 属性

`.name: "ConnectionUnavailableError"`
:   错误名称。

### ServerResponseError

继承自: `SurrealError`

当无法将响应解析为 PRC 响应时抛出此错误。与 `RpcResponseError` 不同。

#### 属性

`.name: "ServerResponseError"`
:   错误名称。

#### 解决方法

通常不会抛出此错误，但如果抛出，则可能是这个 SDK 支持的 SurrelDB 版本和处理 RPC 请求的 SurrealDB 版本不一致。

## CBOR

### CborError

继承自: `SurrealError`

这是 `@tai-kun/surrealdb/cbor` 明确抛出的与 CBOR 相关的所有错误的基类。它不会被直接抛出。

#### 属性

`.name: "CborError"`
:   错误名称。

### CborWellFormednessError

继承自: `CborError`

#### 属性

这是 `@tai-kun/surrealdb/cbor` 明确抛出的与 CBOR 解码相关的所有错误的基类。它不会被直接抛出。

请参阅 RFC8949 附录 F 中的“ [Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)”。

`.name: "CborWellFormednessError"`
:   错误名称。

### CborTooMuchDataError

继承自: `CborWellFormednessError`

表明存在未使用的输入字节。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

#### 属性

`.name: "CborTooMuchDataError"`
:   错误名称。

#### 解决方法

检查目标字节数组是否是正确的 CBOR 格式。

### CborTooLittleDataError

继承自: `CborWellFormednessError`

表明输入字节不完整。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

#### 属性

`.name: "CborTooLittleDataError"`
:   错误名称。

#### 解决方法

检查目标字节数组是否是正确的 CBOR 格式。

### CborSyntaxError

继承自: `CborWellFormednessError`

表明输入字节与 CBOR 编码格式不匹配。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

#### 属性

`.name: "CborSyntaxError"`
:   错误名称。

#### 解决方法

检查目标字节数组是否是正确的 CBOR 格式。

### CborMaxDepthReachedError

继承自: `CborError`

当在编码或解码 CBOR 时，JavaScript 对象的深度达到最大值时抛出此错误。每次进入对象或数组时，深度都会增加 1。

#### 属性

`.name: "CborMaxDepthReachedError"`
:   错误名称。

`.maxDepth: number`
:   最大深度。

#### 解决方法

放宽可选的 `.maxDepth` 上限，或重新调整数据结构，使其嵌套深度较浅。

```ts
import CborFormatter from "@tai-kun/surrealdb/cbor-formatter";

const cborFormatter = new CborFormatter({
  encode: {
    maxDepth: 1024,
  },
  decode: {
    maxDepth: 1024,
  },
  // ...
})
```

### CborUnsafeMapKeyError

继承自: `CborError`

当在编码或解码 CBOR 时遇到不安全的映射键时抛出此错误。

#### 属性

`.name: "CborUnsafeMapKeyError"`
:   错误名称。

`.key: unknown`
:   被判定为不安全的映射键。

## JSON

### JsonError

继承自: `SurrealError`

这是 `@tai-kun/surrealdb/json` 明确抛出的 JSON 格式器。

#### 属性

`.name: "JsonError"`
:   错误名称。

### JsonUnsafeMapKeyError

继承自: `JsonError`

当在解码 JSON 时遇到不安全的映射键时抛出此错误。

#### 属性

`.name: "JsonUnsafeMapKeyError"`
:   错误名称。

`.key: unknown`
:   被判定为不安全的映射键。
