---
title: Errors
---

## SurrealError

`SurrealError` is the base class that most of the error objects explicitly thrown by this SDK inherit from. This class inherits from the JavaScript `Error` class. This error object is rarely thrown on its own, and typically, its specialized subclasses with specific meanings are thrown instead. It's recommended to use this error object for simple classification when catching errors using the `try-catch` statement, to determine if the caught error is an error thrown explicitly by this SDK.

`.name: "SurrealError"`
:   The error name.

`.message`
:   The error message.

`.stack`
:   The stack trace might be recorded.

`.cause`
:   The cause or context of the error might be set.

## SurrealTypeError

Extends: `SurrealError`

This error is thrown when input values or other validations fail.

`.name: "SurrealTypeError"`
:   The error name.

`.expected`
:   The expected data type.

`.actual`
:   The string representation of the actual value.

## SurrealAggregateError

Extends: `SurrealError`

This error represents an aggregation of multiple errors or error messages.

`.name: "SurrealAggregateError"`
:   The error name.

`.cause: unknown[]`
:   Each element in the array contains an error, error message, or similar information.

## CircularReferenceError

Extends: `SurrealError`

This error is thrown when a circular reference is detected. This primarily occurs during the conversion of JavaScript values to another format, when an object is found to refer back to itself within a parent object.

`.name: "CircularReferenceError"`
:   The error name.

For example, this error is thrown in the following case:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

## NumberRangeError

Extends: `SurrealError`

This error is thrown when a number is outside the expected range.

`.name: "NumberRangeError"`
:   The error name.

`.range`
:   The expected range.

`.actual`
:   The actual value.

`.integer`
:   If `true`, an integer is expected.

## UnsupportedRuntimeError

Extends: `SurrealError`

This error is thrown when it's determined that an unsupported runtime is being used.

`.name: "UnsupportedRuntimeError"`
:   The error name.

## UnreachableError

Extends: `SurrealError`

This error is thrown when unreachable code is reached. If this error is thrown, it's likely that a bug in this SDK was encountered.

`.name: "UnreachableError"`
:   The error name.

## CircularEngineReferenceError

Extends: `CircularReferenceError`

This error is thrown when a circular reference occurs between engines during database connection.

`.name: "CircularEngineReferenceError"`
:   The error name.

`.seen: string[]`
:   A list of protocol names traversed before the circular reference occurred.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the example above, the https protocol engine is configured to use the engine configured for http, but the http protocol engine tries to use the engine configured for https, resulting in a circular reference error.

## EngineNotFoundError

Extends: `SurrealError`

This error is thrown when attempting to connect using a protocol for which no engine is configured.

`.name: "EngineNotFoundError"`
:   The error name.

`.protocol: string`
:   The protocol name of the connection target.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

## ConnectionConflictError

Extends: `SurrealError`

This error is thrown when the client attempts to connect to multiple endpoints simultaneously.

`.name: "ConnectionConflictError"`
:   The error name.

`.endpoint1: string`
:   One of the endpoints.

`.endpoint2: string`
:   The other endpoint.

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

The `.connect` method appends `/rpc` to the end of the passed URL if it doesn't end with `/rpc`. Therefore, if one endpoint URL path ends with `/rpc`, it may not result in an error, contrary to appearances:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

## NamespaceConflictError

Extends: `SurrealError`

This error is thrown when the SDK attempts to switch to multiple different namespaces simultaneously.

`.name: "NamespaceConflictError"`
:   The error name.

`.namespace1: string`
:   One of the namespaces.

`.namespace2: string`
:   The other namespace.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "foo" }),
  db.use({ namespace: "bar" }),
]);
```

## DatabaseConflictError

Extends: `SurrealError`

This error is thrown when the SDK attempts to switch to multiple different databases simultaneously.

`.name: "DatabaseConflictError"`
:   The error name.

`.database1: string`
:   One of the databases.

`.database2: string`
:   The other database.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "baz" database: "foo" }),
  db.use({ namespace: "baz" database: "bar" }),
]);
```

## MissingNamespaceError

Extends: `SurrealError`

This error is thrown when a namespace is not selected before selecting a database. Or, it's also thrown if you try to switch to a state where a database is selected but a namespace is not selected.

`.name: "MissingNamespaceError"`
:   The error name.

`.database: string`
:   The database name.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({ database: "example" }); // throws MissingNamespaceError: The namespace must be specified before the database.
```

## RpcResponseError

Extends: `SurrealError`

This error is thrown when the RPC response indicates an error. There's no issue with the communication or response body decoding based on the connected protocol, but it means that SurrealDB could not process the RPC request.

`.name: "RpcResponseError"`
:   The error name.

`.id?: string`
:   The ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:   Although not explicitly stated in the SurrealDB documentation, it's likely the error code from JSON-RPC.

## QueryFailedError

Extends: `SurrealAggregateError`

This error is thrown when the query fails.

`.name: "QueryFailedError"`
:   The error name.

`.cause: string[]`
:   A list of errors.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

## Closed

Extends: `SurrealError`

This error indicates that the connection has been forcibly closed.

`.name: "Closed"`
:   The error name.

For example, you get this error in the following case:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## EngineError

Extends: `SurrealError`

This error indicates that it originated from the engine. It's emitted via event listeners.

`.name: "EngineError"`
:   The error name.

`.fatal: boolean | undefined`
:   Indicates whether this error is fatal.

## HttpEngineError

Extends: `EngineError`

This error indicates that it originated from the HTTP engine. Currently, it's only defined and not used.

`.name: "HttpEngineError"`
:   The error name.

## WebSocketEngineError

Extends: `EngineError`

This error indicates that it originated from the WebSocket engine. It's used when parsing the response body fails before finding the RPC request ID, when an error event is received from the WebSocket object, or when the WebSocket connection is closed.

`.name: "WebSocketEngineError"`
:   The error name.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that the "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates that an error occurred within the "open" event handler registered by the WebSocket engine. It's often the case that `StateTransitionError` occurred during the transition from the connecting state to the connected state.
    - `3152`: Indicates that an error occurred within the "message" event handler registered by the WebSocket engine. Many causes can be considered, but it's likely that `ResponseError` or `RpcResponseError` was thrown within the event handler. Tracing back, the cause may be a malformed SurrealQL custom query requested in the `.query()` method, or a request with invalid RPC parameters. In that case, the RPC caller method (by default) times out and fails after 5 seconds.
    - `3153`: Indicates that the ping transmission or reception failed. This may be a temporary error, but if it continues to be received, there may be a connection issue.
    - `3154`: Indicates that an error occurred within the "close" event handler registered by the WebSocket engine. It's often the case that `StateTransitionError` occurred during the transition from the disconnecting state to the disconnected state.
:   Note that the following status codes are excluded from the above. This SDK does not treat them as errors:
    - `1000`: Normal disconnection.
    - `1001`: Early disconnection is common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` may be the class defined in the global variable by the runtime, or it may be the class of the `ws` SDK.

## StateTransitionError

Extends: `SurrealAggregateError`

This error is thrown when a event listener fails to execute during a state transition.

`.name: "StateTransitionError"`
:   The error name.

`.from: string`
:   The state at the beginning of the state transition.

`.to: string`
:   The target state for the transition.

`.fallback: string`
:   The alternative target state for the transition if it fails. If it's the same value as `.to`, it means that the transition was forced.

For example, this error is thrown in the following case:

```ts
import { Surreal } from "@tai-kun/surrealdb";
import { CONNECTING } from "@tai-kun/surrealdb/engine";

await using db = new Surreal();

db.on(CONNECTING, () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

## ConnectionUnavailableError

Extends: `SurrealError`

This error is thrown when attempting to send an RPC request while not connected.

`.name: "ConnectionUnavailableError"`
:   The error name.

## ResponseError

Extends: `SurrealError`

This error is thrown when a response cannot be parsed as an PRC response. This differs from `RpcResponseError`.

`.name: "ResponseError"`
:   The error name.

## CborError

Extends: `SurrealError`

This is the class that all CBOR-related errors explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. This is never thrown directly.

`.name: "CborError"`
:   The error name.

## CborWellFormednessError

Extends: `CborError`

This is the class that all CBOR decoding-related errors explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. This is never thrown directly.

Refer to "Well-Formedness Errors and Examples" in Appendix F of RFC8949: [https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)

`.name: "CborWellFormednessError"`
:   The error name.

## CborTooMuchDataError

Extends: `CborWellFormednessError`

This indicates that there are unconsumed input bytes remaining.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

`.name: "CborTooMuchDataError"`
:   The error name.

## CborTooLittleDataError

Extends: `CborWellFormednessError`

This indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

`.name: "CborTooLittleDataError"`
:   The error name.

## CborSyntaxError

Extends: `CborWellFormednessError`

This indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

`.name: "CborSyntaxError"`
:   The error name.

## CborMaxDepthReachedError

Extends: `CborError`

This error is thrown when the depth of the JavaScript object reaches the maximum value during CBOR encoding or decoding. The depth increases by 1 for each object or array entry.

`.name: "CborMaxDepthReachedError"`
:   The error name.

`.maxDepth: number`
:   The maximum depth.

## CborUnsafeMapKeyError

Extends: `CborError`

This error is thrown when an unsafe map key is encountered during CBOR encoding or decoding.

`.name: "CborUnsafeMapKeyError"`
:   The error name.

`.key: unknown`
:   The map key that was determined to be unsafe.
