---
title: Errors
---

## SurrealError

`SurrealError` is a base class that almost all error objects explicitly thrown by this SDK inherit from. This class inherits from the JavaScript `Error` class. This error object is rarely thrown by itself. Usually, an inherited error object with a special meaning is thrown. We recommend using it to easily classify whether an error supplemented by a `try-catch` construct or similar is an error explicitly thrown by this SDK.

`.name: "SurrealError"`
:   The error name.

`.message`
:   The error message.

`.stack`
:   May contain a stack trace.

`.cause`
:   May be set to the cause or context of the error.

## SurrealTypeError

Inherits: `SurrealError`

This error is thrown when an input value or other validation fails.

`.name: "SurrealTypeError"`
:   The error name.

`.expected`
:   The expected data format.

`.actual`
:   The string representation of the actual value.

## SurrealAggregateError

Inherits: `SurrealError`

This is an error that aggregates multiple errors or error messages.

`.name: "SurrealAggregateError"`
:   The error name.

`.cause: unknown[]`
:   Each element in the array contains an error, error message, etc.

## CircularReferenceError

Inherits: `SurrealError`

This error is thrown when a circular reference is detected. It is mainly thrown during the process of converting JavaScript values to another format, when the same object as the parent object is detected.

`.name: "CircularReferenceError"`
:   The error name.

For example, this error is thrown in the following case:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

## NumberRangeError

Inherits: `SurrealError`

This error is thrown when a numeric value is outside the allowed range.

`.name: "NumberRangeError"`
:   The error name.

`.range`
:   The expected range.

`.actual`
:   The actual value.

`.integer`
:   If `true`, an integer is expected.

## UnsupportedRuntimeError

Inherits: `SurrealError`

This error is thrown when it is determined that an unsupported runtime is being used.

`.name: "UnsupportedRuntimeError"`
:   The error name.

## UnreachableError

Inherits: `SurrealError`

This error is thrown when unreachable code is reached. If this error is thrown, you have probably encountered a bug in this SDK.

`.name: "UnreachableError"`
:   The error name.

## CircularEngineReferenceError

Inherits: `CircularReferenceError`

This error is thrown when a circular reference occurs between engines when connecting to a database.

`.name: "CircularEngineReferenceError"`
:   The error name.

`.seen: string[]`
:   A list of protocol names that were passed through before the circular reference occurred.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the example above, a circular reference error is thrown because the https protocol engine is configured to use the http engine, while the http protocol engine is configured to use the https engine.

## EngineNotFoundError

Inherits: `SurrealError`

This error is thrown when attempting to connect with a protocol for which no engine is configured.

`.name: "EngineNotFoundError"`
:   The error name.

`.protocol: string`
:   The name of the protocol to connect to.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

## ConnectionConflictError

Inherits: `SurrealError`

This error is thrown when a client attempts to connect to multiple endpoints simultaneously.

`.name: "ConnectionConflictError"`
:   The error name.

`.endpoint1: string`
:   One of the endpoints.

`.endpoint2: string`
:   The other endpoint.

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

The `.connect` method appends `/rpc` to the end of the passed URL if it does not end with `/rpc`. Therefore, if the URL path of one of the endpoints ends with `/rpc`, it may not result in an error, contrary to its appearance:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

## NamespaceConflictError

Inherits: `SurrealError`

This error is thrown when the SDK attempts to switch to multiple different namespaces at the same time.

`.name: "NamespaceConflictError"`
:   The error name.

`.namespace1: string`
:   One of the namespaces.

`.namespace2: string`
:   The other namespace.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "foo" }),
  db.use({ namespace: "bar" }),
]);
```

## DatabaseConflictError

Inherits: `SurrealError`

This error is thrown when the SDK attempts to switch to multiple different databases at the same time.

`.name: "DatabaseConflictError"`
:   The error name.

`.database1: string`
:   One of the databases.

`.database2: string`
:   The other database.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "baz", database: "foo" }),
  db.use({ namespace: "baz", database: "bar" }),
]);
```

## MissingNamespaceError

Inherits: `SurrealError`

This error is thrown if a namespace is not selected before selecting a database. It is also thrown if you try to deselect a namespace while a database is selected.

`.name: "MissingNamespaceError"`
:   The error name.

`.database: string`
:   The database name.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({ database: "example" }); // throws MissingNamespaceError: The namespace must be specified before the database.
```

## RpcResponseError

Inherits: `SurrealError`

This error is thrown when the RPC response indicates an error. There is no problem with the communication using the connected protocol or the decoding of the response body, but it means that SurrealDB was unable to process the RPC request.

`.name: "RpcResponseError"`
:   The error name.

`.id?: string`
:   The ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:   Although not explicitly stated in the SurrealDB documentation, this is probably a JSON-RPC error code.

## QueryFailedError

Inherits: `SurrealAggregateError`

This error is thrown when a query fails.

`.name: "QueryFailedError"`
:   The error name.

`.cause: string[]`
:   A list of errors.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

## Closed

Inherits: `SurrealError`

This error indicates that the connection was forcibly closed.

`.name: "Closed"`
:   The error name.

For example, you get this error in the following case:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## EngineError

Inherits: `SurrealError`

This indicates that the error originated from the engine. It is dispatched via an event listener.

`.name: "EngineError"`
:   The error name.

`.fatal: boolean | undefined`
:   Indicates whether this error is fatal.

## HttpEngineError

Inherits: `EngineError`

This indicates that the error originated from the HTTP engine. Currently, it is only defined and not used.

`.name: "HttpEngineError"`
:   The error name.

## WebSocketEngineError

Inherits: `EngineError`

This indicates that the error originated from the WebSocket engine. It is used when the response body fails to be parsed before finding the ID identifying the RPC request, when an error event is received from the WebSocket object, or when the WebSocket connection is closed.

`.name: "WebSocketEngineError"`
:   The error name.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that an "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates that an error occurred in the "open" event handler registered by the WebSocket engine. In most cases, a `StateTransitionError` occurs during the transition from the connecting state to the connected state.
    - `3152`: Indicates that an error occurred in the "message" event handler registered by the WebSocket engine. There are a variety of possible causes, but it is highly likely that a `ResponseError` or `RpcResponseError` was thrown in the event handler. The original cause may be that a SurrealQL custom query with incorrect syntax was requested by the `.query()` method, or that a request was made with invalid RPC parameters. In that case, the RPC caller method will time out and fail (by default) in 5 seconds.
    - `3153`: Indicates that sending or receiving a ping failed. This may be a temporary error, but if you are receiving it continuously, the connection may not be maintained.
    - `3154`: Indicates that an error occurred in the "close" event handler registered by the WebSocket engine. In most cases, a `StateTransitionError` occurs during the transition from the disconnecting state to the closed state.
:   Note that the following status codes are excluded from the above. They are not treated as errors in this SDK.
    - `1000`: Normal closure.
    - `1001`: Early closure is common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` can be a class defined in a global variable by the runtime or a class from the `ws` SDK.

## StateTransitionError

Inherits: `SurrealAggregateError`

This error is thrown if an event listener fails to execute during a state transition.

`.name: "StateTransitionError"`
:   The error name.

`.from: string`
:   The state at the start of the state transition.

`.to: string`
:   The state to transition to.

`.fallback: string`
:   An alternative transition destination if the state transition fails. If it is the same value as `.to`, it means that the transition was forced.

For example, this error is thrown in the following case:

```ts
import { Surreal } from "@tai-kun/surrealdb";
import { CONNECTING } from "@tai-kun/surrealdb/engine";

await using db = new Surreal();

db.on(CONNECTING, () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

## ConnectionUnavailableError

Inherits: `SurrealError`

This error is thrown when attempting to send an RPC request in a disconnected state.

`.name: "ConnectionUnavailableError"`
:   The error name.

## ResponseError

Inherits: `SurrealError`

This error is thrown when the response cannot be parsed as a PRC response. This is different from `RpcResponseError`.

`.name: "ResponseError"`
:   The error name.

## CborError

Inherits: `SurrealError`

This is a class that all CBOR-related errors explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. It is never thrown directly.

`.name: "CborError"`
:   The error name.

## CborWellFormednessError

Inherits: `CborError`

This is a class that all CBOR decoding related errors explicitly thrown by `@tai-kun/surrealdb/cbor` inherit from. It is never thrown directly.

See "[Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)" in Appendix F of RFC8949.

`.name: "CborWellFormednessError"`
:   The error name.

## CborTooMuchDataError

Inherits: `CborWellFormednessError`

This indicates that there are unconsumed input bytes remaining.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

`.name: "CborTooMuchDataError"`
:   The error name.

## CborTooLittleDataError

Inherits: `CborWellFormednessError`

This indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

`.name: "CborTooLittleDataError"`
:   The error name.

## CborSyntaxError

Inherits: `CborWellFormednessError`

Indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

`.name: "CborSyntaxError"`
:   The error name.

## CborMaxDepthReachedError

Inherits: `CborError`

This error is thrown when the maximum depth of a JavaScript object is reached during CBOR encoding or decoding. The depth increases by 1 for each object or array entered.

`.name: "CborMaxDepthReachedError"`
:   The error name.

`.maxDepth: number`
:   The maximum depth.

## CborUnsafeMapKeyError

Inherits: `CborError`

This error is thrown when an unsafe map key is encountered during CBOR encoding or decoding.

`.name: "CborUnsafeMapKeyError"`
:   The error name.

`.key: unknown`
:   The map key that was determined to be unsafe.
