---
title: Errors
---

## SurrealError

`SurrealError` is the base class that most error objects explicitly thrown by this library inherit. This class inherits from the JavaScript `Error` class. This error object is rarely thrown on its own, but is basically inherited by an error object that has a special meaning. It is recommended to use it to easily classify whether an error supplemented by a `try-catch` construct is an error explicitly thrown by this library.

`.name: "SurrealError"`
:  Error name.

`.message`
:  Error message.

`.stack`
:  The stack trace may be recorded.

`.cause`
:  The cause or context of the error may be set.

## SurrealTypeError

Inherited from: `SurrealError`

This error is thrown if input validation or other validation fails.

`.name: "SurrealTypeError"`
:  Error name.

`.expected`
:  Expected data format.

`.actual`
:  String representation of the actual value.

## SurrealAggregateError

Inherited from: `SurrealError`

This is an error that aggregates multiple errors and error messages.

`.name: "SurrealAggregateError"`
:  Error name.

`.cause: unknown[]`
:  Each element of the array contains an error, an error message, etc.

## CircularReferenceError

Inherited from: `SurrealError`

This error is thrown if a circular reference is detected. This is mainly thrown when the same object as the parent object is detected in the process of converting a JavaScript value to another format.

`.name: "CircularReferenceError"`
:  Error name.

For example, this error will be thrown in the following case:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

## NumberRangeError

Inherited from: `SurrealError`

This error is thrown if a number takes a value outside the range.

`.name: "NumberRangeError"`
:  Error name.

`.range`
:  Expected range.

`.actual`
:  The actual value.

`.integer`
:  If `true`, an integer is expected.

## UnsupportedRuntimeError

Inherited from: `SurrealError`

This error is thrown if it is determined that an unsupported runtime is being used.

`.name: "UnsupportedRuntimeError"`
:  Error name.

## UnreachableError

Inherited from: `SurrealError`

This error is thrown if unreachable code is reached. If this error is thrown, it probably means that you have encountered a bug in this package.

`.name: "UnreachableError"`
:  Error name.

## CircularEngineReferenceError

Inherited from: `CircularReferenceError`

This error is thrown if a circular reference occurs between engines when connecting to a database.

`.name: "CircularEngineReferenceError"`
:  Error name.

`.seen: string[]`
:  A list of protocol names that have been passed through before a circular reference occurs.

For example, this error will be thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the above example, a circular reference error is thrown because the https protocol engine tries to use the engine set to http, even though it indicates that it uses the engine set to http.

## EngineNotFoundError

Inherited from: `SurrealError`

This error is thrown when trying to connect with a protocol for which no engine is set.

`.name: "EngineNotFoundError"`
:  Error name.

`.protocol: string`
:  The name of the protocol to connect to.

For example, this error will be thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

## ConnectionConflictError

Inherited from: `SurrealError`

This error is thrown when a client attempts to connect to multiple endpoints simultaneously.

`.name: "ConnectionConflictError"`
:  Error name.

`.endpoint1: string`
:  One endpoint.

`.endpoint2: string`
:  The other endpoint.

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

The `.connect` method appends `/rpc` to the end of the passed URL if it doesn't already end in `/rpc`. Therefore, if the URL path of one endpoint ends with `/rpc`, an error may not occur despite its appearance:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

## NamespaceConflictError

Inherited from: `SurrealError`

This error is thrown when the client attempts to switch to multiple different namespaces at the same time.

`.name: "NamespaceConflictError"`
:  Error name.

`.namespace1: string`
:  One namespace.

`.namespace2: string`
:  The other namespace.

For example, this error will be thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "foo" }),
  db.use({ namespace: "bar" }),
]);
```

## DatabaseConflictError

Inherited from: `SurrealError`

This error is thrown when the client attempts to switch to multiple different databases at the same time.

`.name: "DatabaseConflictError"`
:  Error name.

`.database1: string`
:  One database.

`.database2: string`
:  The other database.

For example, this error will be thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "baz" database: "foo" }),
  db.use({ namespace: "baz" database: "bar" }),
]);
```

## MissingNamespaceError

Inherited from: `SurrealError`

This error is thrown if no namespace is selected before selecting a database. This will also be thrown if you try to deselect a namespace while a database is selected.

`.name: "MissingNamespaceError"`
:  Error name.

`.database: string`
:  Database name.

For example, this error will be thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({ database: "example" }); // throws MissingNamespaceError: The namespace must be specified before the database.
```

## RpcResponseError

Inherited from: `SurrealError`

This error is thrown when the RPC response indicates an error. This means that there was no problem with the communication over the connected protocol or decoding the response body, but SurrealDB was unable to process the RPC request.

`.name: "RpcResponseError"`
:  Error name.

`.id?: string`
:  An ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:  Not documented in SurrealDB, but probably a JSON-RPC error code.

## QueryFailedError

Inherited from: `SurrealAggregateError`

This error is thrown when a query fails.

`.name: "QueryFailedError"`
:  Error name.

`.cause: string[]`
:  List of errors.

For example, this error will be thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

## Disconnected

Inherited from: `SurrealError`

This error indicates that the connection was forcibly terminated.

`.name: "Disconnected"`
:  Error name.

For example, you get this error in the following cases:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Disconnected
      reject();
    })

    // ...
  });
});

await db.disconnect({ force: true });
```

## EngineError

Inherited from: `SurrealError`

This indicates an error originating from the engine. Shipped via event listener.

`.name: "EngineError"`
:  Error name.

`.fatal: boolean | undefined`
:  Indicates whether this error is fatal.

## HttpEngineError

Inherited from: `EngineError`

This indicates an error originating from the HTTP engine. Currently only defined and not used.

`.name: "HttpEngineError"`
:  Error name.

## WebSocketEngineError

Inherited from: `EngineError`

This indicates an error originating from the WebSocket engine. It is used when the response body fails to be parsed before finding the ID that identifies the RPC request, when an error event is received from the WebSocket object, or when the WebSocket connection is disconnected.

`.name: "WebSocketEngineError"`
:  Error name.

`.code: number`
:  One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that an "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates an error occurred in the "open" event handler registered by the WebSocket engine. Most likely, a `StateTransitionError` occurred during the transition from connecting to connected.
    - `3152`: Indicates an error occurred in the "message" event handler registered by the WebSocket engine. There are many possible causes, but it is likely that a `ResponseError` or `RpcResponseError` was thrown within the event handler. Tracing back, this could be due to requesting a syntactically incorrect SurrealQL custom query with the `.query()` method, or requesting with invalid RPC parameters. In that case, the method that called the RPC will (by default) time out after 5 seconds and fail.
    - `3153`: Indicates that ping sending or receiving failed. This may be a temporary error, but if you are receiving it continuously, the connection may not be maintained.
    - `3154`: Indicates that an error occurred in the "close" event handler registered by the WebSocket engine. Most likely, a `StateTransitionError` occurred in the middle of transitioning from closing to closed.
:   Note that the following status codes are excluded from the above. They are not treated as errors in this package.
    - `1000`: Closed normally.
    - `1001`: Early closure is common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` is a class defined by the runtime in a global variable or the `ws` package.

## StateTransitionError

Inherited from: `SurrealAggregateError`

This error is thrown when an event listener fails to execute during a state transition.

`.name: "StateTransitionError"`
:  Error name.

`.from: number`
:  The state at the start of the state transition.

`.to: number`
:  The state to transition to.

`.fallback: number`
:  An alternative transition destination if the state transition fails. Same value as `.to` means the transition was forced.

For example, this error will be thrown in the following case:

```ts
import { Surreal } from "@tai-kun/surrealdb";
import { CONNECTING } from "@tai-kun/surrealdb/engine";

await using db = new Surreal();

db.on(CONNECTING, () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

## ConnectionUnavailableError

Inherited from: `SurrealError`

This error is thrown when attempting to send an RPC request in a disconnected state.

`.name: "ConnectionUnavailableError"`
:  Error name.

## ResponseError

Inherited from: `SurrealError`

This error is thrown when the response cannot be parsed as a PRC response. This is different from `RpcResponseError`.

`.name: "ResponseError"`
:  Error name.

## CborError

Inherited from: `SurrealError`

This is the class that all CBOR-related errors explicitly thrown by `@tai-kun/surrealdb/cbor` inherit. It is never thrown directly.

`.name: "CborError"`
:  Error name.

## CborWellFormednessError

Inherited from: `CborError`

This is the class that all CBOR decoding related errors explicitly thrown by `@tai-kun/surrealdb/cbor` inherit. It is never thrown directly.

See "[Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)" in Appendix F of RFC8949.

`.name: "CborWellFormednessError"`
:  Error name.

## CborTooMuchDataError

Inherited from: `CborWellFormednessError`

This indicates that unconsumed input bytes remain.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

`.name: "CborTooMuchDataError"`
:  Error name.

## CborTooLittleDataError

Inherited from: `CborWellFormednessError`

This indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

`.name: "CborTooLittleDataError"`
:  Error name.

## CborSyntaxError

Inherited from: `CborWellFormednessError`

Indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

`.name: "CborSyntaxError"`
:  Error name.

## CborMaxDepthReachedError

Inherited from: `CborError`

This error is thrown if the maximum depth of the JavaScript object is reached when encoding or decoding CBOR. The depth increases by 1 each time you enter an object or array.

`.name: "CborMaxDepthReachedError"`
:  Error name.

`.maxDepth: number`
:  Maximum depth.

## CborUnsafeMapKeyError

Inherited from: `CborError`

Error thrown when unsafe map keys are found when encoding or decoding CBOR.

`.name: "CborUnsafeMapKeyError"`
:  Error name.

`.key: unknown`
:  The map key that was determined to be unsafe.
