---
title: Errors
slug: en/v1/reference/errors
---

## SurrealError

`SurrealError` is the base class that most of the error objects thrown explicitly by this SDK inherit. This class inherits from the JavaScript `Error` class. This error object is rarely thrown alone, and it is generally thrown by an inherited error object with a special meaning. It is recommended to use this error object to easily classify errors that have been caught using `try-catch` syntax to determine if they were thrown explicitly by this SDK.

`.name: "SurrealError"`
:   The error name.

`.message`
:   The error message.

`.stack`
:   The stack trace may be recorded.

`.cause`
:   The cause or context of the error may be set.

## SurrealTypeError

Inherits from: `SurrealError`

This is an error that is thrown when an input value or other validation fails.

`.name: "SurrealTypeError"`
:   The error name.

`.expected`
:   The expected data format.

`.actual`
:   A string representation of the actual value.

## SurrealAggregateError

Inherits from: `SurrealError`

This is an error that combines multiple errors or error messages.

`.name: "SurrealAggregateError"`
:   The error name.

`.cause: unknown[]`
:   Each element in the array contains an error or error message.

## CircularReferenceError

Inherits from: `SurrealError`

This error is thrown when a circular reference is detected. It is mainly thrown when a JavaScript value is converted to another format and the same object as the parent object is detected.

`.name: "CircularReferenceError"`
:   The error name.

For example, this error is thrown in the following cases:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

## NumberRangeError

Inherits from: `SurrealError`

This error is thrown when a number has a value outside the allowed range.

`.name: "NumberRangeError"`
:   The error name.

`.range`
:   The expected range.

`.actual`
:   The actual value.

`.integer`
:   If `true`, an integer is expected.

## UnsupportedRuntimeError

Inherits from: `SurrealError`

This error is thrown if it is determined that an unsupported runtime is being used.

`.name: "UnsupportedRuntimeError"`
:   The error name.

## UnreachableError

Inherits from: `SurrealError`

This error is thrown when an unreachable code is reached. If this error is thrown, you have probably encountered a bug in this SDK.

`.name: "UnreachableError"`
:   The error name.

## CircularEngineReferenceError

Inherits from: `CircularReferenceError`

This error is thrown when a circular reference occurs between engines when connecting to the database.

`.name: "CircularEngineReferenceError"`
:   The error name.

`.seen: string[]`
:   List of protocol names that were traversed before the circular reference occurred.

For example, this error is thrown in the following cases:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the example above, the https protocol engine indicates that it will use the engine set to http, but the http protocol engine tries to use the engine set to https, resulting in a circular reference error.

## EngineNotFoundError

Inherits from: `SurrealError`

This error is thrown when you try to connect with a protocol that has no engine configured.

`.name: "EngineNotFoundError"`
:   The error name.

`.protocol: string`
:   The name of the protocol to connect to.

For example, this error is thrown in the following cases:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

## ConnectionConflictError

Inherits from: `SurrealError`

This error is thrown when a client tries to connect to multiple endpoints simultaneously.

`.name: "ConnectionConflictError"`
:   The error name.

`.endpoint1: string`
:   One endpoint.

`.endpoint2: string`
:   The other endpoint.

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

The `.connect` method appends `/rpc` to the end of the URL if the path is not ending with `/rpc`. Therefore, if one endpoint's URL path ends with `/rpc`, the error may not occur, contrary to appearances:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

## NamespaceConflictError

Inherits from: `SurrealError`

This error is thrown when the SDK tries to switch to multiple different namespaces at the same time.

`.name: "NamespaceConflictError"`
:   The error name.

`.namespace1: string`
:   One namespace.

`.namespace2: string`
:   The other namespace.

For example, this error is thrown in the following cases:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "foo" }),
  db.use({ namespace: "bar" }),
]);
```

## DatabaseConflictError

Inherits from: `SurrealError`

This error is thrown when the SDK tries to switch to multiple different databases at the same time.

`.name: "DatabaseConflictError"`
:   The error name.

`.database1: string`
:   One database.

`.database2: string`
:   The other database.

For example, this error is thrown in the following cases:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "baz" database: "foo" }),
  db.use({ namespace: "baz" database: "bar" }),
]);
```

## MissingNamespaceError

Inherits from: `SurrealError`

This error is thrown if a namespace is not selected before a database is selected. Or it is thrown even if a database is selected, but the namespace remains unselected.

`.name: "MissingNamespaceError"`
:   The error name.

`.database: string`
:   The database name.

For example, this error is thrown in the following cases:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({ database: "example" }); // throws MissingNamespaceError: The namespace must be specified before the database.
```

## RpcResponseError

Inherits from: `SurrealError`

This error is thrown if the RPC response indicates an error. There is no problem with communication or decoding the response body using the connected protocol, but it means that SurrealDB cannot process the RPC request.

`.name: "RpcResponseError"`
:   The error name.

`.id?: string`
:   The ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:   It is not specified in the SurrealDB documentation, but it is likely the JSON-RPC error code.

## QueryFailedError

Inherits from: `SurrealAggregateError`

This error is thrown if the query failed.

`.name: "QueryFailedError"`
:   The error name.

`.cause: string[]`
:   A list of errors.

For example, this error is thrown in the following cases:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

## Disconnected

Inherits from: `SurrealError`

This error indicates that the connection was forcibly terminated.

`.name: "Disconnected"`
:   The error name.

For example, you get this error in the following cases:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Disconnected
      reject();
    })

    // ...
  });
});

await db.disconnect({ force: true });
```

## EngineError

Inherits from: `SurrealError`

This indicates that the error is due to the engine. It is sent via the event listener.

`.name: "EngineError"`
:   The error name.

`.fatal: boolean | undefined`
:   Indicates whether this error is fatal.

## HttpEngineError

Inherits from: `EngineError`

This indicates that the error is due to the HTTP engine. It is currently defined only and not used.

`.name: "HttpEngineError"`
:   The error name.

## WebSocketEngineError

Inherits from: `EngineError`

This indicates that the error is due to the WebSocket engine. It is used when parsing the response body fails before finding the RPC request ID, when an error event is received from the WebSocket object, or when the WebSocket connection is closed.

`.name: "WebSocketEngineError"`
:   The error name.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that the "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates that an error occurred in the "open" event handler registered by the WebSocket engine. It is often the case that `StateTransitionError` occurs during the transition from the connecting state to the connected state.
    - `3152`: Indicates that an error occurred in the "message" event handler registered by the WebSocket engine. There are many possible causes, but it is likely that `ResponseError` or `RpcResponseError` was thrown in the event handler. Tracing back, it is likely that the cause is requesting an incorrect grammatical SurrealQL custom query in the `.query()` method or requesting with invalid RPC parameters. In that case, the RPC caller method (by default) times out after 5 seconds and fails.
    - `3153`: Indicates that pinging failed. This may be a temporary error, but if you continue to receive it, you may not be able to maintain the connection.
    - `3154`: Indicates that an error occurred in the "close" event handler registered by the WebSocket engine. It is often the case that `StateTransitionError` occurs during the transition from the disconnecting state to the disconnected state.
:   Note that the following status codes are excluded from above. This SDK does not treat them as errors.
    - `1000`: The connection is closed successfully.
    - `1001`: Early disconnections are common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` is a class defined by the runtime in a global variable, or a class of the `ws` SDK.

## StateTransitionError

Inherits from: `SurrealAggregateError`

This error is thrown if the event listener fails to execute during a state transition.

`.name: "StateTransitionError"`
:   The error name.

`.from: number`
:   The state at the start of the state transition.

`.to: number`
:   The destination state of the transition.

`.fallback: number`
:   The alternative destination for the state transition if it fails. If it is the same value as `.to`, it means that the transition was forced.

For example, this error is thrown in the following cases:

```ts
import { Surreal } from "@tai-kun/surrealdb";
import { CONNECTING } from "@tai-kun/surrealdb/engine";

await using db = new Surreal();

db.on(CONNECTING, () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

## ConnectionUnavailableError

Inherits from: `SurrealError`

This error is thrown if you try to send an RPC request while not connected.

`.name: "ConnectionUnavailableError"`
:   The error name.

## ResponseError

Inherits from: `SurrealError`

This error is thrown if the response cannot be parsed as a PRC response. It is different from `RpcResponseError`.

`.name: "ResponseError"`
:   The error name.

## CborError

Inherits from: `SurrealError`

This is the base class that all errors related to CBOR thrown explicitly by `@tai-kun/surrealdb/cbor` inherit. It is never thrown directly.

`.name: "CborError"`
:   The error name.

## CborWellFormednessError

Inherits from: `CborError`

This is the base class that all errors related to CBOR decoding thrown explicitly by `@tai-kun/surrealdb/cbor` inherit. It is never thrown directly.

Refer to "[Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)" in Appendix F of RFC8949.

`.name: "CborWellFormednessError"`
:   The error name.

## CborTooMuchDataError

Inherits from: `CborWellFormednessError`

Indicates that there are unconsumed input bytes remaining.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

`.name: "CborTooMuchDataError"`
:   The error name.

## CborTooLittleDataError

Inherits from: `CborWellFormednessError`

Indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

`.name: "CborTooLittleDataError"`
:   The error name.

## CborSyntaxError

Inherits from: `CborWellFormednessError`

Indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

`.name: "CborSyntaxError"`
:   The error name.

## CborMaxDepthReachedError

Inherits from: `CborError`

This error is thrown when the depth of a JavaScript object reaches the maximum value during CBOR encoding or decoding. The depth increases by 1 each time you enter an object or array.

`.name: "CborMaxDepthReachedError"`
:   The error name.

`.maxDepth: number`
:   The maximum depth.

## CborUnsafeMapKeyError

Inherits from: `CborError`

This error is thrown when an unsafe map key is found during CBOR encoding or decoding.

`.name: "CborUnsafeMapKeyError"`
:   The error name.

`.key: unknown`
:   The map key that was deemed unsafe.
