---
title: Errors
slug: en/v1/reference/errors
---

## SurrealError

`SurrealError` is the base class that most of the error objects thrown explicitly by this SDK inherit from. This class inherits the `Error` class of JavaScript. This error object is rarely thrown alone, and it is usually the descendant error objects with special meanings that are thrown. It is recommended to use it to easily classify errors caught by the `try-catch` syntax, etc., to determine if the error was explicitly thrown by this SDK.

`.name: "SurrealError"`
:   The error name.

`.message`
:   The error message.

`.stack`
:   The stack trace may be recorded.

`.cause`
:   The cause or context of the error may be set.

## SurrealTypeError

Inherits from: `SurrealError`

This is the error thrown when input values or other validations fail.

`.name: "SurrealTypeError"`
:   The error name.

`.expected`
:   The expected data format.

`.actual`
:   The string representation of the actual value.

## SurrealAggregateError

Inherits from: `SurrealError`

This is an error that aggregates multiple errors or error messages.

`.name: "SurrealAggregateError"`
:   The error name.

`.cause: unknown[]`
:   Each element of the array contains an error, an error message, etc.

## CircularReferenceError

Inherits from: `SurrealError`

This is the error thrown when a circular reference is detected. It is mainly thrown when converting a JavaScript value to another format and an object that is the same as the parent object is detected.

`.name: "CircularReferenceError"`
:   The error name.

For example, this error is thrown in the following case:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

## NumberRangeError

Inherits from: `SurrealError`

This is the error thrown when a number has a value outside the range.

`.name: "NumberRangeError"`
:   The error name.

`.range`
:   The expected range.

`.actual`
:   The actual value.

`.integer`
:   If `true`, an integer is expected.

## UnsupportedRuntimeError

Inherits from: `SurrealError`

This is the error thrown when it is determined that an unsupported runtime is being used.

`.name: "UnsupportedRuntimeError"`
:   The error name.

## UnreachableError

Inherits from: `SurrealError`

This is the error thrown when unreachable code is reached. If this error is thrown, you are probably encountering a bug in this SDK.

`.name: "UnreachableError"`
:   The error name.

## CircularEngineReferenceError

Inherits from: `CircularReferenceError`

This is the error thrown when a circular reference occurs between engines when connecting to a database.

`.name: "CircularEngineReferenceError"`
:   The error name.

`.seen: string[]`
:   A list of protocol names that were traversed before the circular reference occurred.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the above example, the https protocol engine is set to use the engine that is set to http, but the http protocol engine is trying to use the engine that is set to https, so a circular reference error is thrown.

## EngineNotFoundError

Inherits from: `SurrealError`

This is the error thrown when you try to connect with a protocol that does not have an engine set up.

`.name: "EngineNotFoundError"`
:   The error name.

`.protocol: string`
:   The protocol name of the connection destination.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

## ConnectionConflictError

Inherits from: `SurrealError`

This is the error thrown when the client tries to connect to multiple endpoints simultaneously.

`.name: "ConnectionConflictError"`
:   The error name.

`.endpoint1: string`
:   One of the endpoints.

`.endpoint2: string`
:   The other endpoint.

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

The `.connect` method appends `/rpc` to the URL path if it does not end with it. Therefore, if the URL path of one of the endpoints ends with `/rpc`, it may not result in an error, contrary to appearances:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

## NamespaceConflictError

Inherits from: `SurrealError`

This is the error thrown when the SDK tries to switch to multiple different namespaces at the same time.

`.name: "NamespaceConflictError"`
:   The error name.

`.namespace1: string`
:   One of the namespaces.

`.namespace2: string`
:   The other namespace.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "foo" }),
  db.use({ namespace: "bar" }),
]);
```

## DatabaseConflictError

Inherits from: `SurrealError`

This is the error thrown when the SDK tries to switch to multiple different databases at the same time.

`.name: "DatabaseConflictError"`
:   The error name.

`.database1: string`
:   One of the databases.

`.database2: string`
:   The other database.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "baz" database: "foo" }),
  db.use({ namespace: "baz" database: "bar" }),
]);
```

## MissingNamespaceError

Inherits from: `SurrealError`

This is the error thrown when a namespace is not selected before selecting a database. Alternatively, it is also thrown if you try to set the namespace to an unselected state while a database is selected.

`.name: "MissingNamespaceError"`
:   The error name.

`.database: string`
:   The database name.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({ database: "example" }); // throws MissingNamespaceError: The namespace must be specified before the database.
```

## RpcResponseError

Inherits from: `SurrealError`

This is the error thrown when the RPC response indicates an error. This does not mean that there is a problem with the communication or response body decoding due to the connected protocol, but rather that SurrealDB was unable to process the RPC request.

`.name: "RpcResponseError"`
:   The error name.

`.id?: string`
:   The ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:   Although it is not stated in the SurrealDB documentation, it is probably the JSON-RPC error code.

## QueryFailedError

Inherits from: `SurrealAggregateError`

This is the error thrown when a query fails.

`.name: "QueryFailedError"`
:   The error name.

`.cause: string[]`
:   A list of errors.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

## Disconnected

Inherits from: `SurrealError`

This error indicates that the connection has been forcibly terminated.

`.name: "Disconnected"`
:   The error name.

For example, you will get this error in the following case:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Disconnected
      reject();
    })

    // ...
  });
});

await db.disconnect({ force: true });
```

## EngineError

Inherits from: `SurrealError`

This indicates that the error originated from the engine. It is dispatched via the event listener.

`.name: "EngineError"`
:   The error name.

`.fatal: boolean | undefined`
:   Indicates whether this error is fatal.

## HttpEngineError

Inherits from: `EngineError`

This indicates that the error originated from the HTTP engine. Currently, it is only defined and not used.

`.name: "HttpEngineError"`
:   The error name.

## WebSocketEngineError

Inherits from: `EngineError`

This indicates that the error originated from the WebSocket engine. It is used when the response body cannot be parsed before the RPC request ID is found, when an error event is received from the WebSocket object, when the WebSocket connection is disconnected, etc.

`.name: "WebSocketEngineError"`
:   The error name.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that the "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates that an error occurred in the "open" event handler registered by the WebSocket engine. In most cases, a `StateTransitionError` occurs during the transition from the connecting state to the connected state.
    - `3152`: Indicates that an error occurred in the "message" event handler registered by the WebSocket engine. While there are many possible causes, it is likely that a `ResponseError` or `RpcResponseError` was thrown in the event handler. Tracing back to the source, it is likely caused by requesting a custom SurrealQL query with incorrect syntax in the `.query()` method or requesting with invalid RPC parameters. In that case, the calling method of the RPC (by default) will timeout after 5 seconds and fail.
    - `3153`: Indicates that the ping failed to be sent or received. This may be a temporary error, but if you continue to receive it, you may not be able to maintain the connection.
    - `3154`: Indicates that an error occurred in the "close" event handler registered by the WebSocket engine. In most cases, a `StateTransitionError` occurs during the transition from the disconnecting state to the disconnected state.
:   Note that the following status codes are excluded from above. This SDK does not treat them as errors.
    - `1000`: Connection closed normally.
    - `1001`: Early disconnections are common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` may be a class defined by the runtime in a global variable, or a class from the `ws` SDK.

## StateTransitionError

Inherits from: `SurrealAggregateError`

This is the error thrown when the event listener fails to execute during state transition.

`.name: "StateTransitionError"`
:   The error name.

`.from: number`
:   The state when the state transition starts.

`.to: number`
:   The target state of the transition.

`.fallback: number`
:   Alternative transition destination if state transition fails. If it is the same as `.to`, it means that the transition was forced.

For example, this error is thrown in the following case:

```ts
import { Surreal } from "@tai-kun/surrealdb";
import { CONNECTING } from "@tai-kun/surrealdb/engine";

await using db = new Surreal();

db.on(CONNECTING, () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

## ConnectionUnavailableError

Inherits from: `SurrealError`

This is the error thrown when you try to send an RPC request in an unconnected state.

`.name: "ConnectionUnavailableError"`
:   The error name.

## ResponseError

Inherits from: `SurrealError`

This is the error thrown when the response cannot be parsed as a PRC response. This is different from `RpcResponseError`.

`.name: "ResponseError"`
:   The error name.

## CborError

Inherits from: `SurrealError`

This is the class that all CBOR related errors thrown explicitly by `@tai-kun/surrealdb/cbor` inherit from. This is not thrown directly.

`.name: "CborError"`
:   The error name.

## CborWellFormednessError

Inherits from: `CborError`

This is the class that all CBOR decoding related errors thrown explicitly by `@tai-kun/surrealdb/cbor` inherit from. This is not thrown directly.

Refer to Appendix F of RFC8949, "[Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)".

`.name: "CborWellFormednessError"`
:   The error name.

## CborTooMuchDataError

Inherits from: `CborWellFormednessError`

This indicates that there are unconsumed input bytes remaining.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

`.name: "CborTooMuchDataError"`
:   The error name.

## CborTooLittleDataError

Inherits from: `CborWellFormednessError`

This indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

`.name: "CborTooLittleDataError"`
:   The error name.

## CborSyntaxError

Inherits from: `CborWellFormednessError`

This indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

`.name: "CborSyntaxError"`
:   The error name.

## CborMaxDepthReachedError

Inherits from: `CborError`

This is the error thrown when the JavaScript object depth reaches the maximum value during CBOR encoding or decoding. The depth increases by 1 each time you enter an object or array.

`.name: "CborMaxDepthReachedError"`
:   The error name.

`.maxDepth: number`
:   The maximum depth.

## CborUnsafeMapKeyError

Inherits from: `CborError`

This is the error thrown when an unsafe map key is found during CBOR encoding or decoding.

`.name: "CborUnsafeMapKeyError"`
:   The error name.

`.key: unknown`
:   The map key that was determined to be unsafe.
