---
title: Errors
---

## SurrealError

`SurrealError` is the base class that most of the error objects thrown explicitly by this SDK inherit from. This class inherits from JavaScript's `Error` class. This error object is rarely thrown alone, and in general, a special error object with inherited meaning is thrown. It is recommended to use it to easily classify errors caught by the `try-catch` syntax as errors explicitly thrown by this SDK.

`.name: "SurrealError"`
:   The error name.

`.message`
:   The error message.

`.stack`
:   The stack trace may be recorded.

`.cause`
:   The cause or context of the error may be set.

## SurrealTypeError

Inherits from: `SurrealError`

This error is thrown when input values or other validations fail.

`.name: "SurrealTypeError"`
:   The error name.

`.expected`
:   The expected data format.

`.actual`
:   The string representation of the actual value.

## SurrealAggregateError

Inherits from: `SurrealError`

This is an error that summarizes multiple errors or error messages.

`.name: "SurrealAggregateError"`
:   The error name.

`.cause: unknown[]`
:   Each element in the array contains errors or error messages.

## CircularReferenceError

Inherits from: `SurrealError`

This error is thrown when a circular reference is detected. It is mainly thrown when a JavaScript value is converted to another format and the parent object detects the same object.

`.name: "CircularReferenceError"`
:   The error name.

For example, this error is thrown in the following case:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

## NumberRangeError

Inherits from: `SurrealError`

This error is thrown when a number has a value outside the range.

`.name: "NumberRangeError"`
:   The error name.

`.range`
:   The expected range.

`.actual`
:   The actual value.

`.integer`
:   If `true`, an integer is expected.

## UnsupportedRuntimeError

Inherits from: `SurrealError`

This error is thrown when it is determined that an unsupported runtime is being used.

`.name: "UnsupportedRuntimeError"`
:   The error name.

## UnreachableError

Inherits from: `SurrealError`

This error is thrown when unreachable code is reached. If this error is thrown, you have probably encountered a bug in this SDK.

`.name: "UnreachableError"`
:   The error name.

## CircularEngineReferenceError

Inherits from: `CircularReferenceError`

This error is thrown when a circular reference occurs between engines when connecting to the database.

`.name: "CircularEngineReferenceError"`
:   The error name.

`.seen: string[]`
:   A list of protocol names traversed until the circular reference occurs.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the above example, the https protocol engine indicates that it uses the engine set for http, but the http protocol engine tries to use the engine set for https, resulting in a circular reference error.

## EngineNotFoundError

Inherits from: `SurrealError`

This error is thrown when you try to connect using a protocol for which no engine is configured.

`.name: "EngineNotFoundError"`
:   The error name.

`.protocol: string`
:   The protocol name of the connection destination.

For example, this error is thrown in the following case:

```ts
const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

## ConnectionConflictError

Inherits from: `SurrealError`

This error is thrown when the client attempts to connect to multiple endpoints simultaneously.

`.name: "ConnectionConflictError"`
:   The error name.

`.endpoint1: string`
:   One endpoint.

`.endpoint2: string`
:   The other endpoint.

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

The `.connect` method adds `/rpc` to the end of the URL if it does not end with `/rpc`. Therefore, if the URL path of one endpoint ends in `/rpc`, it may not result in an error contrary to its appearance:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

## NamespaceConflictError

Inherits from: `SurrealError`

This error is thrown when the SDK tries to switch to multiple namespaces at the same time.

`.name: "NamespaceConflictError"`
:   The error name.

`.namespace1: string`
:   One namespace.

`.namespace2: string`
:   The other namespace.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "foo" }),
  db.use({ namespace: "bar" }),
]);
```

## DatabaseConflictError

Inherits from: `SurrealError`

This error is thrown when the SDK tries to switch to multiple databases at the same time.

`.name: "DatabaseConflictError"`
:   The error name.

`.database1: string`
:   One database.

`.database2: string`
:   The other database.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.signin({ user: "root", pass: "root" });
await Promise.all([
  db.use({ namespace: "baz" database: "foo" }),
  db.use({ namespace: "baz" database: "bar" }),
]);
```

## MissingNamespaceError

Inherits from: `SurrealError`

This error is thrown when the namespace is not selected before selecting the database. Alternatively, it is also thrown when you try to switch to a state where the namespace is unselected while the database is selected.

`.name: "MissingNamespaceError"`
:   The error name.

`.database: string`
:   The database name.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({ database: "example" }); // throws MissingNamespaceError: The namespace must be specified before the database.
```

## RpcResponseError

Inherits from: `SurrealError`

This error is thrown when the RPC response indicates an error. There is no problem with the communication by the connected protocol or the decoding of the response body, but it means that SurrealDB cannot process the RPC request.

`.name: "RpcResponseError"`
:   The error name.

`.id?: string`
:   The ID that identifies the RPC request. The ID always starts with `<method name>_`.

`.code: number`
:   While not explicitly documented in the SurrealDB documentation, it is likely to be the JSON-RPC error code.

## QueryFailedError

Inherits from: `SurrealAggregateError`

This error is thrown when the query fails.

`.name: "QueryFailedError"`
:   The error name.

`.cause: string[]`
:   A list of errors.

For example, this error is thrown in the following case:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

## Disconnected

Inherits from: `SurrealError`

This error indicates that the connection has been forcibly terminated.

`.name: "Disconnected"`
:   The error name.

For example, you get this error in the following case:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Disconnected
      reject();
    })

    // ...
  });
});

await db.disconnect({ force: true });
```

## EngineError

Inherits from: `SurrealError`

This indicates that the error originated from the engine. It is sent via the event listener.

`.name: "EngineError"`
:   The error name.

`.fatal: boolean | undefined`
:   Indicates whether this error is fatal.

## HttpEngineError

Inherits from: `EngineError`

This indicates that the error originated from the HTTP engine. Currently, it is only defined and not used.

`.name: "HttpEngineError"`
:   The error name.

## WebSocketEngineError

Inherits from: `EngineError`

This indicates that the error originated from the WebSocket engine. It is used when parsing the response body fails before finding the RPC request identification ID, when an error event is received from the WebSocket object, or when the WebSocket connection is disconnected.

`.name: "WebSocketEngineError"`
:   The error name.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that an "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates that an error occurred in the "open" event handler registered by the WebSocket engine. It is often a `StateTransitionError` that occurs during the transition from the connecting state to the connected state.
    - `3152`: Indicates that an error occurred in the "message" event handler registered by the WebSocket engine. There are many possible causes, but the `ResponseError` or `RpcResponseError` is likely to have been thrown in the event handler. Tracing back to the origin, the cause may be that you requested an incorrect grammar SurrealQL custom query using the `.query()` method or that you requested it with invalid RPC parameters. In that case, the calling method of the RPC will time out and fail after 5 seconds (by default).
    - `3153`: Indicates that the ping was not sent or received successfully. It may be a temporary error, but if you continue to receive it, you may not be able to maintain the connection.
    - `3154`: Indicates that an error occurred in the "close" event handler registered by the WebSocket engine. It is often a `StateTransitionError` that occurs during the transition from the disconnecting state to the disconnected state.
:   The following status codes are excluded from the above. This SDK does not treat them as errors.
    - `1000`: The connection has been successfully closed.
    - `1001`: Early disconnections are common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` may be a class defined by the runtime in a global variable, or it may be a class in the `ws` SDK.

## StateTransitionError

Inherits from: `SurrealAggregateError`

This error is thrown when the execution of the event listener fails during the state transition.

`.name: "StateTransitionError"`
:   The error name.

`.from: number`
:   The state at the start of the state transition.

`.to: number`
:   The destination state of the transition.

`.fallback: number`
:   An alternative destination for the state transition if it fails. If it is the same value as `.to`, it means that the transition was forced.

For example, this error is thrown in the following case:

```ts
import { Surreal } from "@tai-kun/surrealdb";
import { CONNECTING } from "@tai-kun/surrealdb/engine";

await using db = new Surreal();

db.on(CONNECTING, () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

## ConnectionUnavailableError

Inherits from: `SurrealError`

This error is thrown when you try to send an RPC request while disconnected.

`.name: "ConnectionUnavailableError"`
:   The error name.

## ResponseError

Inherits from: `SurrealError`

This error is thrown when the response cannot be parsed as a PRC response. It differs from `RpcResponseError`.

`.name: "ResponseError"`
:   The error name.

## CborError

Inherits from: `SurrealError`

This is the class that all errors related to CBOR thrown explicitly by `@tai-kun/surrealdb/cbor` inherit from. This is never thrown directly.

`.name: "CborError"`
:   The error name.

## CborWellFormednessError

Inherits from: `CborError`

This is the class that all errors related to CBOR decoding thrown explicitly by `@tai-kun/surrealdb/cbor` inherit from. This is never thrown directly.

Refer to "Well-Formedness Errors and Examples" in Appendix F of RFC8949 [https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-).

`.name: "CborWellFormednessError"`
:   The error name.

## CborTooMuchDataError

Inherits from: `CborWellFormednessError`

Indicates that there are unconsumed input bytes left.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

`.name: "CborTooMuchDataError"`
:   The error name.

## CborTooLittleDataError

Inherits from: `CborWellFormednessError`

Indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

`.name: "CborTooLittleDataError"`
:   The error name.

## CborSyntaxError

Inherits from: `CborWellFormednessError`

Indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

`.name: "CborSyntaxError"`
:   The error name.

## CborMaxDepthReachedError

Inherits from: `CborError`

This error is thrown when the depth of the JavaScript object reaches the maximum value during CBOR encoding or decoding. The depth increases by 1 each time you enter an object or array.

`.name: "CborMaxDepthReachedError"`
:   The error name.

`.maxDepth: number`
:   The maximum depth.

## CborUnsafeMapKeyError

Inherits from: `CborError`

This error is thrown when an unsafe map key is found during CBOR encoding or decoding.

`.name: "CborUnsafeMapKeyError"`
:   The error name.

`.key: unknown`
:   The map key that was determined to be unsafe.
