---
title: 错误
slug: zh-CN/v2/guides/errors
---

## 概述

某些错误对象可能具有 `.cause` 属性。在大多数情况下，其类型为 `unknown`，并且其值可能会在将来发生更改，恕不另行通知。

## 通用

### SurrealError

`SurrealError` 是这个 SDK 显式抛出的几乎所有错误对象的基类。这个类继承了 JavaScript 的 `Error` 类。这个错误对象很少单独抛出，通常抛出的是继承自它的具有特定含义的错误对象。建议在 `try-catch` 语句中使用它来简单地分类这个 SDK 显式抛出的错误。

#### 属性

`.name: "SurrealError"`
:   错误名称。

`.message`
:   错误消息。

`.stack`
:   可能记录了堆栈跟踪。

`.cause`
:   可能设置了导致错误的原因或上下文。

### SurrealTypeError

继承自：`SurrealError`

当输入值或其他验证失败时抛出此错误。

#### 属性

`.name: "SurrealTypeError"`
:   错误名称。

`.expected`
:   预期的数据类型。

`.actual`
:   实际值的字符串表示形式。

#### 解决方法

沿着堆栈跟踪找到导致输入数据类型不符合预期的原因。

### SurrealValueError

继承自：`SurrealError`

当输入值或其他验证失败时抛出此错误。

#### 属性

`.name: "SurrealValueError"`
:   错误名称。

`.expected`
:   预期的数据类型。

`.actual`
:   实际的值。

#### 解决方法

沿着堆栈跟踪找到导致输入数据类型不符合预期的原因。

### SurrealAggregateError

继承自：`SurrealError`

这是多个错误或错误消息的集合。

#### 属性

`.name: "SurrealAggregateError"`
:   错误名称。

`.cause: unknown[]`
:   数组的每个元素都包含错误或错误消息等。

### CircularReferenceError

继承自：`SurrealError`

当检测到循环引用时抛出此错误。它主要在将 JavaScript 值转换为其他格式的过程中抛出，例如当检测到父对象包含自身时。

#### 属性

`.name: "CircularReferenceError"`
:   错误名称。

例如，在以下情况下会抛出此错误：

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

#### 解决方法

此错误不仅在 `toSurql` 函数中抛出，它是一个常见的错误。您需要仔细调试对象内部，查看是否包含自身。

### NumberRangeError

继承自：`SurrealError`

当数字超出范围时抛出此错误。

#### 属性

`.name: "NumberRangeError"`
:   错误名称。

`.range`
:   预期的范围。

`.actual`
:   实际的值。

`.integer`
:   如果为 `true`，则表示期望为整数。

#### 解决方法

沿着堆栈跟踪找到导致输入数据类型不符合预期的原因。

### UnsupportedRuntimeError

继承自：`SurrealError`

当检测到使用不支持的运行时时抛出此错误。

#### 属性

`.name: "UnsupportedRuntimeError"`
:   错误名称。

#### 解决方法

您需要避免使用该运行时，或者使用 polyfill 并充分测试。

### UnreachableError

继承自：`SurrealError`

当到达无法到达的代码时抛出此错误。如果抛出此错误，则您可能遇到了这个 SDK 的 bug。

#### 属性

`.name: "UnreachableError"`
:   错误名称。

#### 解决方法

您可以通过以下 URL 报告此问题：

[https://github.com/tai-kun/surrealdb.js/issues](https://github.com/tai-kun/surrealdb.js/issues)

## 客户端

### CircularEngineReferenceError

继承自：`CircularReferenceError`

当连接到数据库时，如果引擎之间存在循环引用，则会抛出此错误。

#### 属性

`.name: "CircularEngineReferenceError"`
:   错误名称。

`.seen: string[]`
:   导致循环引用的协议名称列表。

例如，在以下情况下会抛出此错误：

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

在上面的示例中，https 协议引擎指示使用 http 引擎，但 http 协议引擎指示使用 https 引擎，从而导致循环引用错误。

#### 解决方法

不要将字符串作为协议名称的值，而是使用引擎的具体实现来代替：

```ts del={6} ins={7-10}
import { initSurreal } from "@tai-kun/surrealdb";
import HttpEngine from "@tai-kun/surrealdb/engines/http";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    http: config => new HttpEngine({
      ...config,
      // fetch: <your custom fetch function>
    }),
    https: "http",
  },
  // ...
});
```

### EngineNotFoundError

继承自：`SurrealError`

当尝试使用未设置引擎的协议连接时抛出此错误。

#### 属性

`.name: "EngineNotFoundError"`
:   错误名称。

`.protocol: string`
:   连接到的协议名称。

例如，在以下情况下会抛出此错误：

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https protocol engine found.
```

#### 解决方法

检查 `engines` 属性，确认是否可以根据连接到的端点的协议创建引擎。

```ts ins={6}
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
    https: "http",
  },
  // ...
});
```

### ConnectionConflictError

继承自：`SurrealError`

当客户端尝试同时连接到多个端点时抛出此错误。

#### 属性

`.name: "ConnectionConflictError"`
:   错误名称。

`.endpoint1: string`
:   一个端点。

`.endpoint2: string`
:   另一个端点。

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:11298"); // throws ConnectionConflictError: Connection conflict between http://localhost:8000/rpc and http://localhost:11298/rpc.
```

`.connect` 方法会在传递的 URL 的路径没有以 `/rpc` 结尾时将 `/rpc` 追加到末尾。因此，如果一个端点的 URL 路径以 `/rpc` 结尾，则即使看起来并不冲突，也可能会抛出错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

#### 解决方法

在调用 `.connect` 方法之前，可以调用 `.close` 方法，以连接到任何端点。

```ts ins={6}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.close();
await db.connect("http://localhost:11298");
```

### MissingNamespaceError

继承自：`SurrealError`

当在选择数据库之前没有选择命名空间时抛出此错误。或者，当尝试在选择数据库的情况下将命名空间设置为未选择状态时也会抛出此错误。

#### 属性

`.name: "MissingNamespaceError"`
:   错误名称。

`.database: string`
:   数据库名称。

例如，在以下情况下会抛出此错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  database: "example",
}); // throws MissingNamespaceError: The namespace must be specified before the database.
```

#### 解决方法

如果要选择数据库，请确保也选择命名空间。

```ts ins={7}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  namespace: "example",
  database: "example",
});
```

### RpcResponseError

继承自：`SurrealError`

当 RPC 响应表示错误时抛出此错误。这意味着连接的协议的通信和响应正文的解码都没有问题，但 SurrealDB 无法处理 RPC 请求。

#### 属性

`.name: "RpcResponseError"`
:   错误名称。

`.id?: string`
:   识别 RPC 请求的 ID。ID 始终以 `<方法名>_` 开头。

`.code: number`
:   SurrealDB 文档中没有明确说明，它可能是一个 JSON-RPC 错误代码。

#### 解决方法

有各种各样的原因，但可能是这个 SDK 支持的 SurrealDB 版本与处理 RPC 请求的 SurrealDB 版本不一致。

### QueryFailedError

继承自：`SurrealAggregateError`

当查询失败时抛出此错误。

#### 属性

`.name: "QueryFailedError"`
:   错误名称。

`.cause: string[]`
:   错误列表。

例如，在以下情况下会抛出此错误：

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

#### 解决方法

检查 SurrelQL 语法是否正确。

### Closed

继承自：`SurrealError`

表明连接已强制关闭。

#### 属性

`.name: "Closed"`
:   错误名称。

例如，在以下情况下会获得此错误：

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## 引擎

### EngineError

继承自：`SurrealError`

表明这是由引擎引起的错误。通过事件监听器发出。

#### 属性

`.name: "EngineError"`
:   错误名称。

`.fatal: boolean | undefined`
:   表明这个错误是否是致命的。

### HttpEngineError

继承自：`EngineError`

表明这是由 HTTP 引擎引起的错误。目前仅定义，尚未使用。

#### 属性

`.name: "HttpEngineError"`
:   错误名称。

### WebSocketEngineError

继承自：`EngineError`

表明这是由 WebSocket 引擎引起的错误。在找到识别 RPC 请求的 ID 之前解析响应正文失败时，从 WebSocket 对象接收错误事件时，以及断开 WebSocket 连接时使用。

这个 SDK 使用 `315x` 作为自定义状态码。这个范围在 [IANA](https://www.iana.org/assignments/websocket/websocket.xml#close-code-number) 中是未分配的状态码。

#### 属性

`.name: "WebSocketEngineError"`
:   错误名称。

`.code: number`
:   以下状态码之一：
    - `1000`~`1015`: [MDN 参考](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: 表示从 `WebSocket`[^1] 的实例接收了 "error" 事件。
    - `3151`: 表示 WebSocket 引擎注册的 "open" 事件处理程序中发生错误。这通常是在从连接中状态到连接中状态的转换过程中发生了 `StateTransitionError`。
    - `3152`: 表示 WebSocket 引擎注册的 "message" 事件处理程序中发生错误。可能有很多原因，但最有可能的是在事件处理程序中抛出了 `ServerResponseError` 或 `RpcResponseError`。可能是由于使用了无效的 RPC 参数进行请求。在这种情况下，RPC 的调用方方法（默认情况下）将在 5 秒后超时并失败。在 SurrealDB v2.0.2 之前的版本中，它可能会因为更广泛的原因而超时。
    - `3153`: 表示 ping 的发送或接收失败。这可能是一个临时错误，但如果您一直收到它，则可能无法保持连接。
    - `3154`: 表示 WebSocket 引擎注册的 "close" 事件处理程序中发生错误。这通常是在从断开连接状态到断开连接状态的转换过程中发生了 `StateTransitionError`。
:   请注意，除了以下状态码以外的所有状态码都会被这个 SDK 视为错误：
    - `1000`: 连接已成功关闭。
    - `1001`: 常见的早期关闭。
    - `1004`: 保留。
    - `1005`: 保留。
    - `1006`: 保留。
    - `1015`: 保留。

^1: `WebSocket` 可以是运行时在全局变量中定义的类，也可以是 `ws` 的类。

#### 解决方法

`1002`,`1003`,`1007`...`1011`,`1014`,`3150`,`3151`,`3154`
:   可能没有自动恢复这些状态码的方法。您需要修改运行时、SurrealDB 的设置或硬编码的实现。

`3152`
:   检查传递给方法的参数（即 RPC 请求的内容）是否正确。

`1012`,`1013`,`3153`
:   您可以尝试使用实验性功能 [`autoReconnect()`](/v2/experimental/auto-reconnect) 来自动恢复。

### StateTransitionError

继承自：`SurrealAggregateError`

当在状态转换期间执行事件监听器失败时抛出此错误。

#### 属性

`.name: "StateTransitionError"`
:   错误名称。

`.from: string`
:   开始状态转换时的状态。

`.to: string`
:   转换到的状态。

`.fallback: string`
:   如果状态转换失败，则回退到的状态。如果与 `.to` 相同，则表示已强制转换。

例如，在以下情况下会抛出此错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

db.on("connecting", () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

### ConnectionUnavailableError

继承自：`SurrealError`

当尝试在未连接的情况下发送 RPC 请求时抛出此错误。

#### 属性

`.name: "ConnectionUnavailableError"`
:   错误名称。

### ServerResponseError

继承自：`SurrealError`

当无法将响应解析为 PRC 响应时抛出此错误。它与 `RpcResponseError` 不同。

#### 属性

`.name: "ServerResponseError"`
:   错误名称。

#### 解决方法

通常不应该抛出此错误，但如果抛出了，则可能是这个 SDK 支持的 SurrelDB 版本与处理 RPC 请求的 SurrealDB 版本不一致。

## CBOR

### CborError

继承自：`SurrealError`

这是 `@tai-kun/surrealdb/cbor` 显式抛出的所有与 CBOR 相关的错误的基类。它不会直接抛出。

#### 属性

`.name: "CborError"`
:   错误名称。

### CborWellFormednessError

继承自：`CborError`

#### 属性

这是 `@tai-kun/surrealdb/cbor` 显式抛出的所有与 CBOR 解码相关的错误的基类。它不会直接抛出。

请参阅 RFC8949 的附录 F 中的“ [Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)”。

`.name: "CborWellFormednessError"`
:   错误名称。

### CborTooMuchDataError

继承自：`CborWellFormednessError`

表明存在未消费的输入字节。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

#### 属性

`.name: "CborTooMuchDataError"`
:   错误名称。

#### 解决方法

检查要解码的字节数组是否为正确的 CBOR 格式。

### CborTooLittleDataError

继承自：`CborWellFormednessError`

表明输入字节不完整。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

#### 属性

`.name: "CborTooLittleDataError"`
:   错误名称。

#### 解决方法

检查要解码的字节数组是否为正确的 CBOR 格式。

### CborSyntaxError

继承自：`CborWellFormednessError`

表明输入字节与 CBOR 的编码格式不一致。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

#### 属性

`.name: "CborSyntaxError"`
:   错误名称。

#### 解决方法

检查要解码的字节数组是否为正确的 CBOR 格式。

### CborMaxDepthReachedError

继承自：`CborError`

当 CBOR 编码或解码时，JavaScript 对象的深度达到最大值时抛出此错误。进入对象或数组时，深度会增加 1。

#### 属性

`.name: "CborMaxDepthReachedError"`
:   错误名称。

`.maxDepth: number`
:   最大深度。

#### 解决方法

您可以放宽可选的 `.maxDepth` 上限，或者重新设计数据结构，使其嵌套更浅。

```ts
import CborFormatter from "@tai-kun/surrealdb/formatters/cbor";

const cborFormatter = new CborFormatter({
  encode: {
    maxDepth: 1024,
  },
  decode: {
    maxDepth: 1024,
  },
  // ...
})
```

### CborUnsafeMapKeyError

继承自：`CborError`

当在 CBOR 编码或解码时遇到不安全的映射键时抛出此错误。

#### 属性

`.name: "CborUnsafeMapKeyError"`
:   错误名称。

`.key: unknown`
:   被判定为不安全的映射键。

## JSON

### JsonError

继承自：`SurrealError`

这是 `@tai-kun/surrealdb/formatters/json` 显式抛出的所有与 JSON 相关的错误的基类。它不会直接抛出。

#### 属性

`.name: "JsonError"`
:   错误名称。

### JsonUnsafeMapKeyError

继承自：`JsonError`

当在 JSON 解码时遇到不安全的映射键时抛出此错误。

#### 属性

`.name: "JsonUnsafeMapKeyError"`
:   错误名称。

`.key: unknown`
:   被判定为不安全的映射键。
