---
title: 错误
slug: zh-CN/v2/guides/errors
---

## 概述

某些错误对象可能设置了 `.cause` 属性。在大多数情况下，它将是 `unknown` 类型，其值可能会在将来更改而不会另行通知。

## 通用错误

### SurrealError

`SurrealError` 是此 SDK 显式抛出的几乎所有错误对象的基类。该类继承自 JavaScript 的 `Error` 类。很少单独抛出此错误对象，通常会抛出具有特定含义的子类错误对象。建议使用它来简单地分类在 `try-catch` 语句中捕获的错误，以判断该错误是否是由此 SDK 显式抛出的。

#### 属性

`.name: "SurrealError"`
:   错误名称。

`.message`
:   错误消息。

`.stack`
:   可能记录了堆栈跟踪。

`.cause`
:   可能设置了导致错误的原因或上下文。

### SurrealTypeError

继承自：`SurrealError`

当输入值或其他验证失败时抛出此错误。

#### 属性

`.name: "SurrealTypeError"`
:   错误名称。

`.expected`
:   预期的数据格式。

`.actual`
:   实际值的字符串表示形式。

#### 解决方法

沿着堆栈跟踪查找导致未输入预期数据格式的原因。

### SurrealValueError

继承自：`SurrealError`

当输入值或其他验证失败时抛出此错误。

#### 属性

`.name: "SurrealValueError"`
:   错误名称。

`.expected`
:   预期的数据格式。

`.actual`
:   实际值。

#### 解决方法

沿着堆栈跟踪查找导致未输入预期数据格式的原因。

### SurrealAggregateError

继承自：`SurrealError`

这是一个包含多个错误或错误消息的错误。

#### 属性

`.name: "SurrealAggregateError"`
:   错误名称。

`.cause: unknown[]`
:   数组中的每个元素都包含错误或错误消息等。

### CircularReferenceError

继承自：`SurrealError`

当检测到循环引用时抛出此错误。主要是在将 JavaScript 值转换为其他格式的过程中，当检测到与父对象相同的对象时抛出。

#### 属性

`.name: "CircularReferenceError"`
:   错误名称。

`.reference: unknown`
:   发生循环引用的值。

例如，在以下情况下会抛出此错误：

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

#### 解决方法

此错误也可能在除 `toSurql` 函数之外的其他地方抛出。需要仔细调试对象内部，以确保其中不包含该对象本身。

### NumberRangeError

继承自：`SurrealError`

当数值超出范围时抛出此错误。

#### 属性

`.name: "NumberRangeError"`
:   错误名称。

`.range`
:   预期范围。

`.actual`
:   实际值。

`.integer`
:   如果为 `true`，则表示预期为整数。

#### 解决方法

沿着堆栈跟踪查找导致未输入预期数据格式的原因。

### UnsupportedRuntimeError

继承自：`SurrealError`

当判断正在使用不受支持的运行时环境时抛出此错误。

#### 属性

`.name: "UnsupportedRuntimeError"`
:   错误名称。

#### 解决方法

要么不要使用该运行时环境，要么使用 polyfill 并充分测试。

### UnreachableError

继承自：`SurrealError`

当遇到不可达的代码时抛出此错误。如果遇到此错误，则可能遇到了此 SDK 的错误。

#### 属性

`.name: "UnreachableError"`
:   错误名称。

#### 解决方法

可以通过以下 URL 提交此问题：

[https://github.com/tai-kun/surrealdb.js/issues](https://github.com/tai-kun/surrealdb.js/issues)

## 客户端

### CircularEngineReferenceError

继承自：`CircularReferenceError`

当在连接到数据库时，在引擎之间出现循环引用时抛出此错误。

#### 属性

`.name: "CircularEngineReferenceError"`
:   错误名称。

`.reference: string`
:   发生循环引用的模式名称。

`.seen: string[]`
:   发生循环引用之前经过的模式名称列表。

例如，在以下情况下会抛出此错误：

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

在上面的示例中，尽管 https 协议的引擎指示使用 http 的引擎，但 http 协议的引擎尝试使用 https 的引擎，从而导致循环引用错误。

#### 解决方法

不要将字符串指定为协议名称的值，而是将它替换为创建引擎的具体实现：

```ts del={6} ins={7-10}
import { initSurreal } from "@tai-kun/surrealdb";
import HttpEngine from "@tai-kun/surrealdb/http-engine";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    http: config => new HttpEngine({
      ...config,
      // fetch: <your custom fetch function>
    }),
    https: "http",
  },
  // ...
});
```

### EngineNotFoundError

继承自：`SurrealError`

当尝试使用未设置引擎的协议连接时抛出此错误。

#### 属性

`.name: "EngineNotFoundError"`
:   错误名称。

`.scheme: string`
:   要连接的协议名称。

例如，在以下情况下会抛出此错误：

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https scheme engine found.
```

#### 解决方法

检查 `engines` 属性以确定连接目标终结点的协议是否可以创建引擎。

```ts ins={6}
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
    https: "http",
  },
  // ...
});
```

### ConnectionConflictError

继承自：`SurrealError`

当客户端尝试同时连接到多个终结点时抛出此错误。

#### 属性

`.name: "ConnectionConflictError"`
:   错误名称。

`.endpoint1: string`
:   已连接的终结点。

`.endpoint2: string`
:   另一个终结点。

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("ws://localhost:8000");
await db.connect("ws://localhost:1129"); // throws ConnectionConflictError: An attempt was made to connect to ws://localhost:1129/rpc while ws://localhost:8000/rpc was already connected.
```

`.connect` 方法会在传递的 URL 的路径不以 `/rpc` 结尾时，在末尾添加它。因此，如果一方终结点的 URL 路径以 `/rpc` 结尾，则它可能不会抛出错误，这与表面看起来不同：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

#### 解决方法

通过调用 `.close` 方法，可以在调用 `.connect` 方法之前连接到任何终结点。

```ts ins={6}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.close();
await db.connect("http://localhost:11298");
```

### MissingNamespaceError

继承自：`SurrealError`

当在选择数据库之前未选择命名空间时抛出此错误。或者，即使选择了数据库，但仍尝试将其设置为未选择命名空间状态时也会抛出此错误。

#### 属性

`.name: "MissingNamespaceError"`
:   错误名称。

`.database: string`
:   数据库名称。

例如，在以下情况下会抛出此错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  database: "example",
}); // throws MissingNamespaceError: The namespace must be specified before the database.
```

#### 解决方法

选择数据库时，应同时选择命名空间。

```ts ins={7}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  namespace: "example",
  database: "example",
});
```

### RpcResponseError

继承自：`SurrealError`

当 RPC 响应指示错误时抛出此错误。连接的协议、响应正文的解码等都没有问题，但这意味着 SurrealDB 无法处理 RPC 请求。

#### 属性

`.name: "RpcResponseError"`
:   错误名称。

`.id?: string`
:   标识 RPC 请求的 ID。ID 始终以 `<方法名>_` 开头。

`.code: number`
:   SurrealDB 文档中没有明确说明，但可能代表 JSON-RPC 错误代码。

#### 解决方法

可能有各种原因，但可能是此 SDK 支持的 SurrelDB 版本与处理 RPC 请求的 SurrealDB 版本不一致。

### QueryFailedError

继承自：`SurrealAggregateError`

当查询失败时抛出此错误。

#### 属性

`.name: "QueryFailedError"`
:   错误名称。

`.cause: string[]`
:   错误列表。

例如，在以下情况下会抛出此错误：

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

#### 解决方法

确认 SurrelQL 语法是否正确。

### Closed

继承自：`SurrealError`

表示连接已被强制终止。

#### 属性

`.name: "Closed"`
:   错误名称。

例如，在以下情况下会收到此错误：

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## 引擎

### EngineError

继承自：`SurrealError`

表示这是由引擎导致的错误。它通过事件监听器发出。

#### 属性

`.name: "EngineError"`
:   错误名称。

`.fatal: boolean | undefined`
:   指示此错误是否为致命错误。

### HttpEngineError

继承自：`EngineError`

表示这是由 HTTP 引擎导致的错误。目前仅定义，尚未使用。

#### 属性

`.name: "HttpEngineError"`
:   错误名称。

### WebSocketEngineError

继承自：`EngineError`

表示这是由 WebSocket 引擎导致的错误。当在找到标识 RPC 请求的 ID 之前解析响应正文失败，或从 WebSocket 对象接收错误事件，或断开 WebSocket 连接时使用。

此 SDK 使用 `315x` 作为自定义状态代码。此范围在 [IANA](https://www.iana.org/assignments/websocket/websocket.xml#close-code-number) 中未分配状态代码。

#### 属性

`.name: "WebSocketEngineError"`
:   错误名称。

`.code: number`
:   以下状态代码之一：
    - `1000`~`1015`: [MDN 参考](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: 表示从 `WebSocket`[^1] 实例收到 "error" 事件。
    - `3151`: 表示 WebSocket 引擎在注册的 "open" 事件处理程序中发生错误。大多数情况下是由于在连接状态到连接状态的转换过程中发生 `StateTransitionError`。
    - `3152`: 表示 WebSocket 引擎在注册的 "message" 事件处理程序中发生错误。可能有各种原因，但最有可能是事件处理程序中抛出了 `ServerResponseError` 或 `RpcResponseError`。可能是由于使用无效的 RPC 参数发送请求导致的。在这种情况下，RPC 的调用方方法（默认情况下）会在 5 秒后超时并失败。在 SurrealDB v2.0.2 之前的版本中，可能存在更广泛的原因导致超时。
    - `3153`: 表示 ping 的发送或接收失败。可能是暂时性错误，但如果持续收到，则可能表示连接无法维持。
    - `3154`: 表示 WebSocket 引擎在注册的 "close" 事件处理程序中发生错误。大多数情况下是由于在断开连接状态到断开连接状态的转换过程中发生 `StateTransitionError`。
:   需要注意的是，上述状态代码中不包含以下状态代码。此 SDK 将其视为非错误。
    - `1000`: 正常断开连接。
    - `1001`: 早期断开连接很常见。
    - `1004`: 保留。
    - `1005`: 保留。
    - `1006`: 保留。
    - `1015`: 保留。

^1: `WebSocket` 可以是运行时在全局变量中定义的类，也可以是 `ws` 的类。

#### 解决方法

`1002`,`1003`,`1007`...`1011`,`1014`,`3150`,`3151`,`3154`
:   可能没有自动恢复此状态代码的方法。需要修改运行时环境、SurrealDB 设置或硬编码的实现。

`3152`
:   检查传递给方法的参数（即 RPC 请求的内容）是否正确。

`1012`,`1013`,`3153`
:   可以使用实验性功能 [`autoReconnect()`](/v2/experimental/auto-reconnect) 来实现自动恢复。

### StateTransitionError

继承自：`SurrealAggregateError`

当状态转换期间事件监听器的执行失败时抛出此错误。

#### 属性

`.name: "StateTransitionError"`
:   错误名称。

`.from: string`
:   状态转换开始时的状态。

`.to: string`
:   目标状态。

`.fallback: string`
:   状态转换失败时的备用目标转换。如果它与 `.to` 相同，则表示已强制进行转换。

例如，在以下情况下会抛出此错误：

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

db.on("connecting", () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

### ConnectionUnavailableError

继承自：`SurrealError`

当尝试在未连接状态下发送 RPC 请求时抛出此错误。

#### 属性

`.name: "ConnectionUnavailableError"`
:   错误名称。

### ServerResponseError

继承自：`SurrealError`

当无法将响应解析为 PRC 响应时抛出此错误。它与 `RpcResponseError` 不同。

#### 属性

`.name: "ServerResponseError"`
:   错误名称。

#### 解决方法

通常不会抛出此错误，但如果抛出，则可能是此 SDK 支持的 SurrelDB 版本与处理 RPC 请求的 SurrealDB 版本不一致。

## CBOR

### CborError

继承自：`SurrealError`

它是 `@tai-kun/surrealdb/cbor` 显式抛出的所有与 CBOR 相关的错误的基类。它不会直接抛出。

#### 属性

`.name: "CborError"`
:   错误名称。

### CborWellFormednessError

继承自：`CborError`

#### 属性

它是 `@tai-kun/surrealdb/cbor` 显式抛出的所有与 CBOR 解码相关的错误的基类。它不会直接抛出。

请参考 RFC8949 附录 F 中的“ [Well-Formedness Errors and Examples](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-)”。

`.name: "CborWellFormednessError"`
:   错误名称。

### CborTooMuchDataError

继承自：`CborWellFormednessError`

表示有未消耗的输入字节剩余。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

#### 属性

`.name: "CborTooMuchDataError"`
:   错误名称。

#### 解决方法

检查要解码的字节数组是否是正确的 CBOR 格式。

### CborTooLittleDataError

继承自：`CborWellFormednessError`

表示输入字节不完整。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

#### 属性

`.name: "CborTooLittleDataError"`
:   错误名称。

#### 解决方法

检查要解码的字节数组是否是正确的 CBOR 格式。

### CborSyntaxError

继承自：`CborWellFormednessError`

表示输入字节与 CBOR 编码格式不匹配。

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

#### 属性

`.name: "CborSyntaxError"`
:   错误名称。

#### 解决方法

检查要解码的字节数组是否是正确的 CBOR 格式。

### CborMaxDepthReachedError

继承自：`CborError`

当在 CBOR 编码或解码期间 JavaScript 对象的深度达到最大值时抛出此错误。每次进入对象或数组时，深度都会增加 1。

#### 属性

`.name: "CborMaxDepthReachedError"`
:   错误名称。

`.maxDepth: number`
:   最大深度。

#### 解决方法

放宽可选的 `.maxDepth` 上限，或重新设计数据结构以使其嵌套较浅。

```ts
import CborFormatter from "@tai-kun/surrealdb/cbor-formatter";

const cborFormatter = new CborFormatter({
  encode: {
    maxDepth: 1024,
  },
  decode: {
    maxDepth: 1024,
  },
  // ...
})
```

### CborUnsafeMapKeyError

继承自：`CborError`

当在 CBOR 编码或解码期间遇到不安全的映射键时抛出此错误。

#### 属性

`.name: "CborUnsafeMapKeyError"`
:   错误名称。

`.key: unknown`
:   被判断为不安全的映射键。

## JSON

### JsonError

继承自：`SurrealError`

它是 `@tai-kun/surrealdb/json` 显式抛出的所有与 JSON-formatter 相关的错误的基类。

#### 属性

`.name: "JsonError"`
:   错误名称。

### JsonUnsafeMapKeyError

继承自：`JsonError`

当在 JSON 解码期间遇到不安全的映射键时抛出此错误。

#### 属性

`.name: "JsonUnsafeMapKeyError"`
:   错误名称。

`.key: unknown`
:   被判断为不安全的映射键。
