---
title: Errors
slug: en/v2/guides/errors
---

## Introduction

Some error objects may have a `.cause` property. In most cases, this is of type `unknown` and the value may change without notice.

## General

### SurrealError

`SurrealError` is the base class inherited by most of the error objects that this SDK throws explicitly. This class inherits from JavaScript's `Error` class. This error object is rarely thrown alone, and it is basically thrown by special error objects with inherited meaning. This is recommended for easy classification of errors caught in `try-catch` syntax, etc., to see if the error was thrown explicitly by this SDK.

#### Properties

`.name: "SurrealError"`
:   Error name.

`.message`
:   Error message.

`.stack`
:   Stack trace may be recorded.

`.cause`
:   The cause or context of the error may be set.

### SurrealTypeError

Inherited from: `SurrealError`

This error is thrown when input values or other validations fail.

#### Properties

`.name: "SurrealTypeError"`
:   Error name.

`.expected`
:   Expected data format.

`.actual`
:   String representation of the actual value.

#### Solution

Follow the stack trace to find the source of the unexpected data format.

### SurrealValueError

Inherited from: `SurrealError`

This error is thrown when input values or other validations fail.

#### Properties

`.name: "SurrealValueError"`
:   Error name.

`.expected`
:   Expected data format.

`.actual`
:   Actual value.

#### Solution

Follow the stack trace to find the source of the unexpected data format.

### SurrealAggregateError

Inherited from: `SurrealError`

This is an error that combines multiple errors or error messages.

#### Properties

`.name: "SurrealAggregateError"`
:   Error name.

`.cause: unknown[]`
:   Each element of the array contains an error or error message.

### CircularReferenceError

Inherited from: `SurrealError`

This error is thrown when a circular reference is detected. This is mainly thrown when converting a JavaScript value to another format, such as when the same object is detected as the parent object.

#### Properties

`.name: "CircularReferenceError"`
:   Error name.

`.reference: unknown`
:   The value where the circular reference occurred.

For example, this error is thrown in cases like this:

```ts
import { toSurql } from "@tai-kun/surrealdb/utils";

const a = {};
a.a = a;

console.log(a); // <ref *1> { a: [Circular *1] }

toSurql(a); // throws CircularReferenceError
```

#### Solution

This error is a common error that can be thrown other than the `toSurql` function. You need to carefully debug whether the object contains the object itself.

### NumberRangeError

Inherited from: `SurrealError`

This error is thrown when a number is out of range.

#### Properties

`.name: "NumberRangeError"`
:   Error name.

`.range`
:   Expected range.

`.actual`
:   Actual value.

`.integer`
:   If `true`, expects an integer.

#### Solution

Follow the stack trace to find the source of the unexpected data format.

### UnsupportedRuntimeError

Inherited from: `SurrealError`

This error is thrown when it is determined that an unsupported runtime is being used.

#### Properties

`.name: "UnsupportedRuntimeError"`
:   Error name.

#### Solution

Either don't use that runtime or polyfill and test thoroughly.

### UnreachableError

Inherited from: `SurrealError`

This error is thrown when unreachable code is reached. If this error is thrown, you have probably encountered a bug in this SDK.

#### Properties

`.name: "UnreachableError"`
:   Error name.

#### Solution

You can raise this issue at the following URL:

[https://github.com/tai-kun/surrealdb.js/issues](https://github.com/tai-kun/surrealdb.js/issues)

## Client

### CircularEngineReferenceError

Inherited from: `CircularReferenceError`

This error is thrown when a circular reference occurs between engines when connecting to the database.

#### Properties

`.name: "CircularEngineReferenceError"`
:   Error name.

`.reference: string`
:   Scheme name where circular reference occurred.

`.seen: string[]`
:   List of scheme names that were traversed before the circular reference occurred.

For example, this error is thrown in cases like this:

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    https: "http",
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws CircularEngineReferenceError: Circular engine reference: http,https
```

In the example above, the https protocol engine is set to use the engine set to http, but the http protocol engine tries to use the engine set to https, so a circular reference error is thrown.

#### Solution

Instead of setting the protocol name specified by the string to the value of another protocol name, replace it with the specific implementation that creates the engine:

```ts del={6} ins={7-10}
import { initSurreal } from "@tai-kun/surrealdb";
import HttpEngine from "@tai-kun/surrealdb/http-engine";

const { Surreal } = initSurreal({
  engines: {
    http: "https",
    http: config => new HttpEngine({
      ...config,
      // fetch: <your custom fetch function>
    }),
    https: "http",
  },
  // ...
});
```

### EngineNotFoundError

Inherited from: `SurrealError`

This error is thrown when you try to connect with a protocol for which no engine is configured.

#### Properties

`.name: "EngineNotFoundError"`
:   Error name.

`.scheme: string`
:   The name of the protocol to connect to.

For example, this error is thrown in cases like this:

```ts
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
  },
  // ...
});

await using db = new Surreal();
await db.connect("https://localhost:8000"); // throws EngineNotFoundError: No https scheme engine found.
```

#### Solution

Check the `engines` property to see if an engine can be created for the protocol of the connecting endpoint.

```ts ins={6}
import { initSurreal } from "@tai-kun/surrealdb";

const { Surreal } = initSurreal({
  engines: {
    http: config => new HttpEngine(config),
    https: "http",
  },
  // ...
});
```

### ConnectionConflictError

Inherited from: `SurrealError`

This error is thrown when the client attempts to connect to multiple endpoints simultaneously.

#### Properties

`.name: "ConnectionConflictError"`
:   Error name.

`.endpoint1: string`
:   Already connected endpoint.

`.endpoint2: string`
:   The other endpoint.

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("ws://localhost:8000");
await db.connect("ws://localhost:1129"); // throws ConnectionConflictError: An attempt was made to connect to ws://localhost:1129/rpc while ws://localhost:8000/rpc was already connected.
```

`.connect` method adds `/rpc` to the end of the URL passed, so the error may not occur, contrary to appearances, if the URL path of one of the endpoints ends in `/rpc`:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.connect("http://localhost:8000/rpc"); // OK!
```

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000/rpc");
await db.connect("http://localhost:8000"); // OK!
```

#### Solution

You can connect to any endpoint by calling the `.close` method before calling the `.connect` method.

```ts ins={6}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

await db.connect("http://localhost:8000");
await db.close();
await db.connect("http://localhost:11298");
```

### MissingNamespaceError

Inherited from: `SurrealError`

This error is thrown when no namespace is selected before selecting a database. Or, it is thrown even if you try to leave the namespace unselected after selecting the database.

#### Properties

`.name: "MissingNamespaceError"`
:   Error name.

`.database: string`
:   Database name.

For example, this error is thrown in cases like this:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  database: "example",
}); // throws MissingNamespaceError: The namespace must be specified before the database.
```

#### Solution

When selecting a database, make sure to also select a namespace.

```ts ins={7}
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.use({
  namespace: "example",
  database: "example",
});
```

### RpcResponseError

Inherited from: `SurrealError`

This error is thrown when the RPC response indicates an error. There are no problems with communication or response body decoding due to the connected protocol, but it means that SurrealDB cannot process the RPC request.

#### Properties

`.name: "RpcResponseError"`
:   Error name.

`.id?: string`
:   The ID that identifies the RPC request. The ID always starts with `<method name>`.

`.code: number`
:   It is not explicitly stated in the SurrealDB documentation, but it is probably the JSON-RPC error code.

#### Solution

There are many possible causes, but the version of SurrelDB that this SDK supports may be different from the version of SurrealDB that processes the RPC request.

### QueryFailedError

Inherited from: `SurrealAggregateError`

This error is thrown when the query fails.

#### Properties

`.name: "QueryFailedError"`
:   Error name.

`.cause: string[]`
:   List of errors.

For example, this error is thrown in cases like this:

```ts
await using db = new Surreal();
await db.connect("http://localhost:8000");

await db.query("OUTPUT 'Hello'"); // throws QueryFailedError: Query failed with 1 error(s)
```

#### Solution

Check if the SurrelQL syntax is correct.

### Closed

Inherited from: `SurrealError`

This error indicates that the connection has been forcibly terminated.

#### Properties

`.name: "Closed"`
:   Error name.

For example, you get this error in cases like this:

```ts
const db = new Surreal();

db.on("<event_name>", ({ signal }) => {
  return new Promise((resolve, reject) => {
    signal.addEventListener("abort", function() {
      console.error(this.reason); // Closed
      reject();
    })

    // ...
  });
});

await db.close({ force: true });
```

## Engine

### EngineError

Inherited from: `SurrealError`

This indicates that the error is due to the engine. It is sent via event listener.

#### Properties

`.name: "EngineError"`
:   Error name.

`.fatal: boolean | undefined`
:   Indicates whether this error is fatal.

### HttpEngineError

Inherited from: `EngineError`

This indicates that the error is due to the HTTP engine. It is currently defined but not used.

#### Properties

`.name: "HttpEngineError"`
:   Error name.

### WebSocketEngineError

Inherited from: `EngineError`

This indicates that the error is due to the WebSocket engine. It is used when the response body fails to parse before finding the RPC request identifier, when an error event is received from the WebSocket object, when the WebSocket connection is disconnected, etc.

This SDK uses `315x` for custom status codes. This range is unassigned in [IANA](https://www.iana.org/assignments/websocket/websocket.xml#close-code-number).

#### Properties

`.name: "WebSocketEngineError"`
:   Error name.

`.code: number`
:   One of the following status codes:
    - `1000`~`1015`: [MDN Reference](https://developer.mozilla.org/docs/Web/API/CloseEvent/code)
    - `3150`: Indicates that the "error" event was received from the `WebSocket`[^1] instance.
    - `3151`: Indicates that an error occurred in the "open" event handler registered by the WebSocket engine. In most cases, a `StateTransitionError` occurs during the transition from the connecting state to the connected state.
    - `3152`: Indicates that an error occurred in the "message" event handler registered by the WebSocket engine. There are many possible causes, but it is likely that a `ServerResponseError` or `RpcResponseError` was thrown in the event handler. It is likely that the request was made with invalid RPC parameters. In this case, the calling method of the RPC (by default) times out after 5 seconds and fails. In versions prior to SurrealDB v2.0.2, it may timeout due to a wider range of causes.
    - `3153`: Indicates that the ping failed to be sent or received. This could be a temporary error, but if you keep receiving it, you may not be able to maintain the connection.
    - `3154`: Indicates that an error occurred in the "close" event handler registered by the WebSocket engine. In most cases, a `StateTransitionError` occurs during the transition from the disconnecting state to the disconnected state.
:   Note that the following status codes are excluded from the above. This SDK does not treat them as errors.
    - `1000`: The connection has been closed normally.
    - `1001`: Early disconnections are common.
    - `1004`: Reserved.
    - `1005`: Reserved.
    - `1006`: Reserved.
    - `1015`: Reserved.

^1: `WebSocket` is either a class defined in the global variable by the runtime or a class of `ws`.

#### Solution

`1002`,`1003`,`1007`...`1011`,`1014`,`3150`,`3151`,`3154`
:   There is probably no automatic way to recover from this status code. You need to fix the runtime, SurrealDB settings, or hardcoded implementation.

`3152`
:   Check if the arguments passed to the method (i.e., the content of the RPC request) are correct.

`1012`,`1013`,`3153`
:   You may be able to automatically recover using the experimental feature [`autoReconnect()`](/v2/experimental/auto-reconnect).

### StateTransitionError

Inherited from: `SurrealAggregateError`

This error is thrown when the event listener fails to execute during the state transition.

#### Properties

`.name: "StateTransitionError"`
:   Error name.

`.from: string`
:   The state at the start of the state transition.

`.to: string`
:   The state to which the transition is intended.

`.fallback: string`
:   Alternative transition destination if the state transition fails. If it is the same value as `.to`, it means that the transition was forced.

For example, this error is thrown in cases like this:

```ts
import { Surreal } from "@tai-kun/surrealdb";

await using db = new Surreal();

db.on("connecting", () => {
  throw new Error("Don't let me connect !!!")
});

await db.connect("http://localhost:8000"); // throws ...
// StateTransitionError: The transition from `3` to `0` failed, falling back to `3`.
//     at <stack trace ...> {
//   cause: [
//     Error: Don't let me connect !!!
//         at <stack trace ...>
//   ],
//   from: 3,
//   to: 0,
//   fallback: 3
// }
```

### ConnectionUnavailableError

Inherited from: `SurrealError`

This error is thrown when you try to send an RPC request in an unconnected state.

#### Properties

`.name: "ConnectionUnavailableError"`
:   Error name.

### ServerResponseError

Inherited from: `SurrealError`

This error is thrown when the response cannot be parsed as a PRC response. This is different from `RpcResponseError`.

#### Properties

`.name: "ServerResponseError"`
:   Error name.

#### Solution

This error should never be thrown normally, but if it is thrown, the version of SurrelDB that this SDK supports may be different from the version of SurrealDB that processes the RPC request.

## CBOR

### CborError

Inherited from: `SurrealError`

This is the class inherited by all errors related to CBOR that are thrown explicitly by `@tai-kun/surrealdb/cbor`. This is never thrown directly.

#### Properties

`.name: "CborError"`
:   Error name.

### CborWellFormednessError

Inherited from: `CborError`

#### Properties

This is the class inherited by all errors related to CBOR decoding that are thrown explicitly by `@tai-kun/surrealdb/cbor`. This is never thrown directly.

Refer to "Well-Formedness Errors and Examples" in Appendix F of RFC8949 [https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-](https://datatracker.ietf.org/doc/html/rfc8949#name-well-formedness-errors-and-).

`.name: "CborWellFormednessError"`
:   Error name.

### CborTooMuchDataError

Inherited from: `CborWellFormednessError`

Indicates that there are input bytes remaining that were not consumed.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.2)

#### Properties

`.name: "CborTooMuchDataError"`
:   Error name.

#### Solution

Check if the byte array to be decoded is in the correct CBOR format.

### CborTooLittleDataError

Inherited from: `CborWellFormednessError`

Indicates that the input bytes are incomplete.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.4)

#### Properties

`.name: "CborTooLittleDataError"`
:   Error name.

#### Solution

Check if the byte array to be decoded is in the correct CBOR format.

### CborSyntaxError

Inherited from: `CborWellFormednessError`

Indicates that the input bytes do not match the CBOR encoding format.

[RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-appendix.f-2.6)

#### Properties

`.name: "CborSyntaxError"`
:   Error name.

#### Solution

Check if the byte array to be decoded is in the correct CBOR format.

### CborMaxDepthReachedError

Inherited from: `CborError`

This error is thrown when the depth of the JavaScript object reaches the maximum value during CBOR encoding or decoding. The depth increases by 1 every time you enter an object or array.

#### Properties

`.name: "CborMaxDepthReachedError"`
:   Error name.

`.maxDepth: number`
:   Maximum depth.

#### Solution

Relax the upper limit of the optional `.maxDepth` option or revise the data structure so that the object nesting is shallow.

```ts
import CborFormatter from "@tai-kun/surrealdb/cbor-formatter";

const cborFormatter = new CborFormatter({
  encode: {
    maxDepth: 1024,
  },
  decode: {
    maxDepth: 1024,
  },
  // ...
})
```

### CborUnsafeMapKeyError

Inherited from: `CborError`

This error is thrown when an unsafe map key is found during CBOR encoding or decoding.

#### Properties

`.name: "CborUnsafeMapKeyError"`
:   Error name.

`.key: unknown`
:   The map key that was determined to be unsafe.

## JSON

### JsonError

Inherited from: `SurrealError`

This is the JSON-formatter that is thrown explicitly by `@tai-kun/surrealdb/json`.

#### Properties

`.name: "JsonError"`
:   Error name.

### JsonUnsafeMapKeyError

Inherited from: `JsonError`

This error is thrown when an unsafe map key is found during JSON decoding.

#### Properties

`.name: "JsonUnsafeMapKeyError"`
:   Error name.

`.key: unknown`
:   The map key that was determined to be unsafe.
